import { MOCK_GET_PERSON_CREDITS } from '@/mocks'
import { describe, expect, it } from 'vitest'
import { getListCredits } from '.'

const MOCK_GET_PERSON_CREDITS_FORMATTED = [
  [
    'Acting',
    {
      '2008': [
        {
          date: '2008-07-22',
          year: 2008,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 1009787,
            original_language: 'en',
            original_title: 'El Tux',
            overview: '',
            popularity: 2.556,
            poster_path: '/pJkdRpaj5HFbxt66xEGVbntnwDI.jpg',
            release_date: '2008-07-22',
            title: 'El Tux',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Bobby Gomez',
            credit_id: '62f0848f176a94007eecbb04',
            order: 0,
          },
        },
      ],
      '2012': [
        {
          date: '2012-08-24',
          year: 2012,
          info: {
            adult: false,
            backdrop_path: '/cuk3Jovfrepygi9ptveDVHjuma.jpg',
            genre_ids: [35],
            id: 119457,
            original_language: 'en',
            original_title: 'General Education',
            overview:
              'O jogador de tênis Levi Collins (Chris Sheffield) conseguiu uma bolsa de estudos para a universidade local, mas esqueceu de contar para os pais que não se formou no colégio. Para conseguir o diploma e entrar na faculdade, o jovem vai ter que frequentar o curso de verão de ciências.',
            popularity: 5.958,
            poster_path: '/ksIoMKlM9zh8WLfvgQJBmVcD0tf.jpg',
            release_date: '2012-08-24',
            title: 'E Agora? Repeti em Ciências',
            video: false,
            vote_average: 4.6,
            vote_count: 11,
            character: 'Andy',
            credit_id: '52fe4c01c3a36847f821d1bb',
            order: 10,
          },
        },
      ],
      '2013': [
        {
          date: '2013-06-21',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 201282,
            original_language: 'en',
            original_title: 'Big Gay Love',
            overview: '',
            popularity: 3.603,
            poster_path: '/wunibAEQA6ceqOTq3yiwaSqCUkK.jpg',
            release_date: '2013-06-21',
            title: 'Big Gay Love',
            video: false,
            vote_average: 4,
            vote_count: 10,
            character: '',
            credit_id: '64a66123cae6320102883b29',
            order: 12,
          },
        },
        {
          date: '2013-06-07',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/kms4PhWfP1Q2jidPLOf26qm0paJ.jpg',
            genre_ids: [35],
            id: 116741,
            original_language: 'en',
            original_title: 'The Internship',
            overview:
              'Billy (Vince Vaughn) e Nick (Owen Wilson) são grandes amigos e trabalham juntos como vendedores de relógios. Eles são pegos de surpresa quando seu chefe (John Goodman) fecha a empresa, por acreditar que o negócio esteja ultrapassado. Com problemas financeiros, eles conseguem a inscrição em uma seleção de estágio no Google. Mesmo sem terem a garantia que serão contratados, eles partem para a sede da empresa e lá precisam lidar com a diferença de idade entre eles e os demais competidores.',
            popularity: 1.337,
            poster_path: '/eJ2yNRyP3QJ36lO81f19ep98eWw.jpg',
            release_date: '2013-06-07',
            title: 'Os Estagiários',
            video: false,
            vote_average: 6.25,
            vote_count: 4049,
            character: 'Zach',
            credit_id: '52fe4b9cc3a36847f820bfed',
            order: 13,
          },
        },
        {
          date: '2013-05-15',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/WtVXVywl1ruqtKBJqjuO5pDWyt.jpg',
            genre_ids: [],
            id: 1011663,
            original_language: 'en',
            original_title: 'Chocolate Milk',
            overview: '',
            popularity: 3.886,
            poster_path: '/wXTNNbRmCU96r1RKw19xnHWU3Ej.jpg',
            release_date: '2013-05-15',
            title: 'Chocolate Milk',
            video: false,
            vote_average: 2,
            vote_count: 1,
            character: 'Phillip Hensler',
            credit_id: '62f5962cb39e35007b094dad',
            order: 1,
          },
        },
      ],
      '2017': [
        {
          date: '2017-10-08',
          year: 2017,
          info: {
            adult: false,
            backdrop_path: '/kmG5pmly0X8bB5SLkvm119j4cnk.jpg',
            genre_ids: [27, 14, 9648, 53, 878],
            id: 480210,
            original_language: 'en',
            original_title: 'Truth or Dare',
            overview: '',
            popularity: 14.997,
            poster_path: '/l5Dyos3xViHP5ROuCi01P9Q6nZA.jpg',
            release_date: '2017-10-08',
            title: 'Truth or Dare',
            video: false,
            vote_average: 5.323,
            vote_count: 124,
            character: 'Holt Thorne',
            credit_id: '59dadaf2c3a368620d0470b2',
            order: 10,
          },
        },
        {
          date: '2017-07-08',
          year: 2017,
          info: {
            adult: false,
            backdrop_path: '/nxGFfz7z9Xz7raIx5uS5DDWf5xt.jpg',
            genre_ids: [],
            id: 633158,
            original_language: 'en',
            original_title: "Cock N' Bull 2",
            overview: '',
            popularity: 1.892,
            poster_path: '/zH8BqbvUe5MD2ZkMIrj5WZf4bur.jpg',
            release_date: '2017-07-08',
            title: "Cock N' Bull 2",
            video: false,
            vote_average: 2,
            vote_count: 2,
            character: '',
            credit_id: '63397e3c38469a007ac4d6f5',
            order: 6,
          },
        },
        {
          date: '2017-01-24',
          year: 2017,
          info: {
            adult: false,
            backdrop_path: '/5Ibx8ATwSSd7jFO5LQcUQlJsFyj.jpg',
            genre_ids: [18, 35, 27],
            id: 441749,
            original_language: 'en',
            original_title: '8 Bodies',
            overview: '',
            popularity: 4.474,
            poster_path: '/4g6jRpRsOH4HyiHW5BVW59qQCvV.jpg',
            release_date: '2017-01-24',
            title: '8 Bodies',
            video: false,
            vote_average: 7,
            vote_count: 1,
            character: 'Gary',
            credit_id: '646c54e62bcf6700fe61fed1',
            order: 3,
          },
        },
      ],
      '2018': [
        {
          date: '2018-09-21',
          year: 2018,
          info: {
            adult: false,
            backdrop_path: '/txf54dz60Hvb4nETdXY1glKa0tV.jpg',
            genre_ids: [53, 10770, 27],
            id: 550148,
            original_language: 'en',
            original_title: 'The Body',
            overview:
              'Um assassino sofisticado, com uma visão cínica da sociedade moderna, acha seu trabalho mais difícil quando ele precisa transportar um corpo na noite de Halloween, mas todos estão apaixonados pelo que consideram ser sua fantasia de assassino.',
            popularity: 15.749,
            poster_path: '/2jtfye3iLzxjpmIVxcfwarPfhQz.jpg',
            release_date: '2018-09-21',
            title: 'O Corpo',
            video: false,
            vote_average: 6.332,
            vote_count: 104,
            character: 'Nick',
            credit_id: '5bb975fec3a368241801e8b9',
            order: 5,
          },
        },
        {
          date: '2018-05-03',
          year: 2018,
          info: {
            adult: false,
            backdrop_path: '/84yj2klZlegwwdE3wFTCW7d6twD.jpg',
            genre_ids: [878, 10751, 12],
            id: 487509,
            original_language: 'en',
            original_title: 'F.R.E.D.I.',
            overview: '',
            popularity: 7.904,
            poster_path: '/ayJCf4MI00lO55hOXVaKGVotEDX.jpg',
            release_date: '2018-05-03',
            title: 'F.R.E.D.I.: A Robô',
            video: false,
            vote_average: 6,
            vote_count: 56,
            character: 'Lopez',
            credit_id: '5ae800909251410d1000f71c',
            order: 10,
          },
        },
        {
          date: '2018-02-09',
          year: 2018,
          info: {
            adult: false,
            backdrop_path: '/fJkh0BPaJOKsllac4iMcyE6m2at.jpg',
            genre_ids: [35, 14, 878],
            id: 416494,
            original_language: 'en',
            original_title: 'Status Update',
            overview:
              'O adolescente Kyle Moore enfrenta dificuldades para se ajustar à nova escola. Os valentões não saem da sua cola, e a garota dos seus sonhos parece ser inalcansável. Mas, quando lhe apresentam um aplicativo que promete realizar todos os seus desejos, a vida do novato muda da água para o vinho.',
            popularity: 27.057,
            poster_path: '/htMuH2YHr6tOWghIMo3lO0QgfwY.jpg',
            release_date: '2018-02-09',
            title: 'Status Update: Perfil dos Sonhos',
            video: false,
            vote_average: 7.346,
            vote_count: 504,
            character: 'Lonnie Gregory',
            credit_id: '57dddd359251417855003fb4',
            order: 2,
          },
        },
      ],
      '2020': [
        {
          date: '2020-12-18',
          year: 2020,
          info: {
            adult: false,
            backdrop_path: '/siegrD8mqIBT3iZkSzvvzjbwDw1.jpg',
            genre_ids: [10751],
            id: 777280,
            original_language: 'en',
            original_title: "Jimmy's Jungle",
            overview: '',
            popularity: 3.58,
            poster_path: '/4M4rkJEcyf2sB4oDLbcY9o4HFqJ.jpg',
            release_date: '2020-12-18',
            title: "Jimmy's Jungle",
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Marvin',
            credit_id: '64d619fcf495ee02942f31d2',
            order: 5,
          },
        },
      ],
      '2021': [
        {
          date: '2021-06-25',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/bbFHu1kyMqV1s1tyVfoBC8tPtmT.jpg',
            genre_ids: [27, 35, 14],
            id: 800497,
            original_language: 'en',
            original_title: 'Werewolves Within',
            overview:
              'Um gasoduto criou divisões na pequena cidade de Beaverfield. Quando uma tempestade de neve prende seus residentes dentro da pousada local, o guarda florestal recém-chegado Finn e a funcionária dos correios Cecily devem tentar manter a paz e descobrir a verdade por trás de uma criatura misteriosa que começou a aterrorizar a comunidade.',
            popularity: 25.422,
            poster_path: '/i17UiQgqHatZxlfaFQsnvPhYhyi.jpg',
            release_date: '2021-06-25',
            title: 'Um Lobo Entre Nós',
            video: false,
            vote_average: 6.039,
            vote_count: 490,
            character: 'Joachim Wolfson',
            credit_id: '6037dcd62790bf0040339b95',
            order: 7,
          },
        },
      ],
      '2022': [
        {
          date: '2022-12-07',
          year: 2022,
          info: {
            adult: false,
            backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
            genre_ids: [16, 12, 14, 35, 28, 10751],
            id: 315162,
            original_language: 'en',
            original_title: 'Puss in Boots: The Last Wish',
            overview:
              'O Gato de Botas descobre que sua paixão pela aventura cobrou seu preço: ele queimou oito de suas nove vidas, deixando-o com apenas uma vida restante. Gato parte em uma jornada épica para encontrar o mítico Último Desejo e restaurar suas nove vidas.',
            popularity: 227.584,
            poster_path: '/atJxZfCaQ7kXRFSfbm8cqAKkns7.jpg',
            release_date: '2022-12-07',
            title: 'Gato de Botas 2: O Último Pedido',
            video: false,
            vote_average: 8.237,
            vote_count: 7270,
            character: 'Perrito (voice)',
            credit_id: '62a970c25541fa00a312f13c',
            order: 2,
          },
        },
        {
          date: '2022-11-04',
          year: 2022,
          info: {
            adult: false,
            backdrop_path: '/1E2OOb3WUBEwHyBwlhV9BIJ1HfO.jpg',
            genre_ids: [35, 878, 18],
            id: 800282,
            original_language: 'en',
            original_title: "I'm Totally Fine",
            overview: '',
            popularity: 3.181,
            poster_path: '/4eCfOPqoE5ezwQCgVGQszwlxdJh.jpg',
            release_date: '2022-11-04',
            title: "I'm Totally Fine",
            video: false,
            vote_average: 6.438,
            vote_count: 16,
            character: 'DJ Twisted Bristle',
            credit_id: '6036e40c4fd141003eae7094',
            order: 3,
          },
        },
        {
          date: '2022-10-08',
          year: 2022,
          info: {
            adult: false,
            backdrop_path: '/qSfeV3QAvBEuB4CnxhLaeblfaio.jpg',
            genre_ids: [35, 27],
            id: 1031206,
            original_language: 'en',
            original_title: 'Cursed Friends',
            overview:
              'Quatro amigos de infância de trinta e poucos anos acordam no Halloween depois de um encontro regado a álcool e percebem que um jogo de previsão de futuro chamado M.A.S.H., que eles jogaram em 2002, está começando a se tornar realidade de maneiras hilariantes e inquietantes. Eles precisam se unir para escapar do destino selvagem que transtornou suas vidas.',
            popularity: 13.799,
            poster_path: '/zKxK1rZ0y3k6SQfRotq0jLMzz2Q.jpg',
            release_date: '2022-10-08',
            title: 'Amizade Amaldiçoada',
            video: false,
            vote_average: 4.611,
            vote_count: 18,
            character: 'Andy',
            credit_id: '633a5ac8ab1bc7007e59b6cc',
            order: 1,
          },
        },
      ],
      '2023': [
        {
          date: '2023-11-13',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
            genre_ids: [16, 10751, 14, 12],
            id: 1022796,
            original_language: 'en',
            original_title: 'Wish',
            overview:
              'No reino mágico de Rosas, Asha é uma moça perspicaz que faz um desejo tão poderoso que é atendido por uma força cósmica: uma pequena esfera de energia ilimitada chamada Star. Juntas, Asha e Star enfrentam o Rei Magnifico pra salvar a comunidade e provar que, quando um ser humano se une à energia das estrelas, coisas maravilhosas podem acontecer.',
            popularity: 311.835,
            poster_path: '/temIXpcua7j5v4FipOxmzTfrB06.jpg',
            release_date: '2023-11-13',
            title: 'Wish: O Poder dos Desejos',
            video: false,
            vote_average: 6.461,
            vote_count: 1198,
            character: 'Gabo (voice)',
            credit_id: '6514a16493bd6900c4dd72e2',
            order: 7,
          },
        },
        {
          date: '2023-08-17',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/1HzL603WOer58xtnrRYdSIL5K04.jpg',
            genre_ids: [35, 12],
            id: 912908,
            original_language: 'en',
            original_title: 'Strays',
            overview:
              'Quando Reggie, um Border Terrier ingênuo e implacavelmente otimista, é abandonado nas ruas da cidade por seu dono, Doug, Reggie tem certeza de que seu amado dono nunca o deixaria de propósito.',
            popularity: 64.015,
            poster_path: '/hfSkDDJiCf6cJpd4R9O9lM1T6hz.jpg',
            release_date: '2023-08-17',
            title: 'Ruim pra Cachorro',
            video: false,
            vote_average: 7.33,
            vote_count: 729,
            character: 'Shitstain (voice)',
            credit_id: '63e3e0ca7304b500c9f5ff5f',
            order: 6,
          },
        },
        {
          date: '2023-08-16',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/xzdOIL7261CWehsHOk3lnP0xqam.jpg',
            genre_ids: [28, 878, 12],
            id: 565770,
            original_language: 'en',
            original_title: 'Blue Beetle',
            overview:
              'Jaime Reyes, um adolescente de origem mexicana que encontra um artefato alienígena que lhe dá um exoesqueleto mecanizado e poderes, tornando-o no Besouro Azul.',
            popularity: 194.158,
            poster_path: '/y5sdkgO4IJMTnkjh9PG7kREPWrP.jpg',
            release_date: '2023-08-16',
            title: 'Besouro Azul',
            video: false,
            vote_average: 6.8,
            vote_count: 2362,
            character: 'Dr. Sanchez',
            credit_id: '62277fbf871b340071c19d2a',
            order: 10,
          },
        },
        {
          date: '2023-02-28',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/1q0EO7ERXprEjgeyBW0E9QEvKT1.jpg',
            genre_ids: [16, 28, 14, 35, 10751],
            id: 1088561,
            original_language: 'en',
            original_title: 'The Trident',
            overview: '',
            popularity: 6.704,
            poster_path: '/7cpvdkdVP8lL3q40ovPeIk3zdbZ.jpg',
            release_date: '2023-02-28',
            title: 'The Trident',
            video: false,
            vote_average: 7.2,
            vote_count: 6,
            character: 'Perrito (voice)',
            credit_id: '63f10dbc15376c008bbfe799',
            order: 3,
          },
        },
      ],
      '2024': [
        {
          date: '2024-04-30',
          year: 2024,
          info: {
            adult: false,
            backdrop_path: '/vWzJDjLPmycnQ42IppEjMpIhrhc.jpg',
            genre_ids: [16, 35, 10751],
            id: 748783,
            original_language: 'en',
            original_title: 'The Garfield Movie',
            overview:
              'Garfield, o mundialmente famoso gato de interior que odeia segundas-feiras e adora lasanha, está prestes a ter uma aventura selvagem ao ar livre! Depois de um reencontro inesperado com seu pai há muito perdido – o desalinhado gato de rua Vic – Garfield e seu amigo canino Odie são forçados a deixar sua vida perfeitamente mimada para se juntarem a Vic em um assalto hilariante e de alto risco.',
            popularity: 1045.031,
            poster_path: '/rC5RqXtFoTkBhNWE1dczwi4dZrX.jpg',
            release_date: '2024-04-30',
            title: 'Garfield - Fora de Casa',
            video: false,
            vote_average: 6.759,
            vote_count: 81,
            character: 'Odie (voice)',
            credit_id: '65541fb753866e00abaa5fee',
            order: 2,
          },
        },
        {
          date: '2024-03-07',
          year: 2024,
          info: {
            adult: false,
            backdrop_path: '/6SLyu9ygASsrOqkCpjAwtyG9PWW.jpg',
            genre_ids: [10751, 878, 28, 35],
            id: 1094556,
            original_language: 'en',
            original_title: 'The Thundermans Return',
            overview:
              'Os Thundermans estão de volta, mas tiveram que retornar a Hiddenville depois que um acidente os tira de seus cargos no combate ao crime.',
            popularity: 129.247,
            poster_path: '/wEquopFw43QCKsBp1fpIabmGlYc.jpg',
            release_date: '2024-03-07',
            title: 'O Retorno dos Thundermans',
            video: false,
            vote_average: 7.2,
            vote_count: 131,
            character: 'Blobbin',
            credit_id: '64b1f6f6e0ca7f01253c7428',
            order: 12,
          },
        },
      ],
      '2025': [
        {
          date: '2025-01-09',
          year: 2025,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [878, 53],
            id: 1084199,
            original_language: 'en',
            original_title: 'Companion',
            overview: '',
            popularity: 4.242,
            poster_path: null,
            release_date: '2025-01-09',
            title: 'Companion',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Eli',
            credit_id: '64863f76028f14013b86351f',
            order: 4,
          },
        },
      ],
      Produção: [
        {
          date: '-',
          year: NaN,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [18, 53],
            id: 1081131,
            original_language: 'en',
            original_title: 'Crossword',
            overview: '',
            popularity: 1.906,
            poster_path: '/cp0rXpgO5whAb4KFYtSRIl2sDbP.jpg',
            release_date: '',
            title: 'Crossword',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: '',
            credit_id: '63d9c39322df2e00df3f573f',
            order: 2,
          },
        },
        {
          date: '-',
          year: NaN,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [18, 14, 878],
            id: 842924,
            original_language: 'en',
            original_title: 'The Life of Chuck',
            overview: '',
            popularity: 4.581,
            poster_path: '/tY0E31quhJrrnTyD7PlGwqpyI8n.jpg',
            release_date: '',
            title: 'The Life of Chuck',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: '',
            credit_id: '653a1b742811a1010b1df916',
            order: 8,
          },
        },
      ],
    },
  ],
  [
    'Production',
    {
      '2013': [
        {
          date: '2013-05-15',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/WtVXVywl1ruqtKBJqjuO5pDWyt.jpg',
            genre_ids: [],
            id: 1011663,
            original_language: 'en',
            original_title: 'Chocolate Milk',
            overview: '',
            popularity: 3.886,
            poster_path: '/wXTNNbRmCU96r1RKw19xnHWU3Ej.jpg',
            release_date: '2013-05-15',
            title: 'Chocolate Milk',
            video: false,
            vote_average: 2,
            vote_count: 1,
            credit_id: '62f59c45abdec00082346ba5',
            department: 'Production',
            job: 'Executive Producer',
          },
        },
        {
          date: '2013-05-15',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/WtVXVywl1ruqtKBJqjuO5pDWyt.jpg',
            genre_ids: [],
            id: 1011663,
            original_language: 'en',
            original_title: 'Chocolate Milk',
            overview: '',
            popularity: 3.886,
            poster_path: '/wXTNNbRmCU96r1RKw19xnHWU3Ej.jpg',
            release_date: '2013-05-15',
            title: 'Chocolate Milk',
            video: false,
            vote_average: 2,
            vote_count: 1,
            credit_id: '62f59e35813cb6007b35a64c',
            department: 'Production',
            job: 'Casting Director',
          },
        },
      ],
      Produção: [
        {
          date: '-',
          year: NaN,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [18, 53],
            id: 1081131,
            original_language: 'en',
            original_title: 'Crossword',
            overview: '',
            popularity: 1.906,
            poster_path: '/cp0rXpgO5whAb4KFYtSRIl2sDbP.jpg',
            release_date: '',
            title: 'Crossword',
            video: false,
            vote_average: 0,
            vote_count: 0,
            credit_id: '6487395b99259c00e2f62558',
            department: 'Production',
            job: 'Executive Producer',
          },
        },
      ],
    },
  ],
]

describe('getListCredits', () => {
  it('deve retornar a lista de créditos formata por data', () => {
    const SUT = getListCredits([...MOCK_GET_PERSON_CREDITS.cast, ...MOCK_GET_PERSON_CREDITS.crew])
    const expected = MOCK_GET_PERSON_CREDITS_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('deve retornar undefined se não passar listCredit', () => {
    // @ts-expect-error
    const SUT1 = getListCredits(undefined)
    const expected1 = undefined
    expect(SUT1).toStrictEqual(expected1)

    // @ts-expect-error
    const SUT2 = getListCredits(null)
    const expected2 = undefined
    expect(SUT2).toStrictEqual(expected2)

    // @ts-expect-error
    const SUT3 = getListCredits('')
    const expected3 = undefined
    expect(SUT3).toStrictEqual(expected3)

    const SUT4 = getListCredits([])
    const expected4 = undefined
    expect(SUT4).toStrictEqual(expected4)
  })
})
