import { MOCK_GET_PERSON_CREDITS } from '@/mocks'
import { describe, expect, it } from 'vitest'
import { getListCredits } from '.'

const MOCK_GET_PERSON_CREDITS_FORMATTED = [
  [
    'Acting',
    {
      '2005': [
        {
          date: '2005-06-21',
          year: 2005,
          info: {
            adult: false,
            backdrop_path: '/vBVRgryngFoqHazyLqFca6xNTeB.jpg',
            genre_ids: [35, 14, 10749],
            id: 9722,
            original_language: 'en',
            original_title: 'Bewitched',
            overview:
              'Isabel (Nicole Kidman) é uma bondosa bruxa, que vive no vale californiano de San Fernando e deseja mudar de vida. Isabel está decidida a renegar seus poderes sobrenaturais e levar uma vida normal. Enquanto isso Jack Wyatt (Will Ferrell), um ator que deseja resgatar sua carreira, se dedica integralmente à nova versão da clássica série de TV "A Feiticeira", exibida nos anos 60, na qual interpretará o personagem Darrin. Por acaso Jack conhece Isabel, por quem sente uma atração imediata. Convencido de que Isabel poderia interpretar a personagem Samantha na série, Jack a convence a se tornar atriz. Por sua vez Isabel vê em Jack a chance de levar uma vida normal, sem precisar usar seus poderes, e por isso aceita o papel.',
            popularity: 25.997,
            poster_path: '/npz3nxmaI2TspQkVoGobgdUdO36.jpg',
            release_date: '2005-06-21',
            title: 'A Feiticeira',
            video: false,
            vote_average: 5.1,
            vote_count: 1491,
            character: 'Bed, Bath and Beyond Shopper',
            credit_id: '5f1e5c8c0bb0760034fb7adb',
            order: 21,
          },
        },
      ],
      '2006': [
        {
          date: '2006-01-16',
          year: 2006,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [35],
            id: 879158,
            original_language: 'en',
            original_title: 'Boom Man',
            overview: '',
            popularity: 1.646,
            poster_path: null,
            release_date: '2006-01-16',
            title: 'Boom Man',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Maria',
            credit_id: '615373f3f04d0100444fd363',
            order: 1,
          },
        },
      ],
      '2009': [
        {
          date: '2009-12-01',
          year: 2009,
          info: {
            adult: false,
            backdrop_path: null,
            genre_ids: [16],
            id: 331258,
            original_language: 'en',
            original_title: 'Handy Manny: Big Motorcycle Adventure',
            overview: '',
            popularity: 2.313,
            poster_path: '/vLjIzErBlLsXfGAqBgxmB6YXtMB.jpg',
            release_date: '2009-12-01',
            title: 'Handy Manny: Big Motorcycle Adventure',
            video: true,
            vote_average: 7.5,
            vote_count: 1,
            character: 'Lola / Aunt Lupe (voice)',
            credit_id: '641626d06a222700c6b39e03',
            order: 9,
          },
        },
      ],
      '2011': [
        {
          date: '2011-05-13',
          year: 2011,
          info: {
            adult: false,
            backdrop_path: '/i7ITE05sYhXl5yBT7dW6ythLSBI.jpg',
            genre_ids: [35, 10749],
            id: 55721,
            original_language: 'en',
            original_title: 'Bridesmaids',
            overview:
              'Lillian (Maya Rudolph) vai se casar e convida a amiga Annie (Kristen Wiig) para ser sua madrinha. Ela, que enfrenta problemas profissionais e amorosos, resolve se dedicar à função de corpo e alma. Só que, logo no primeiro evento organizado, Annie conhece Helen (Rose Byrne), uma bela e rica mulher que quer ser a nova melhor amiga de Lillian. As duas logo passam a disputar a proximidade da amiga, assim como o posto de organizadora do casamento e demais eventos pré-nupciais.',
            popularity: 54.695,
            poster_path: '/fy0uubz7JfImjvCODFHAoPVgSgy.jpg',
            release_date: '2011-05-13',
            title: 'Missão Madrinha de Casamento',
            video: false,
            vote_average: 6.529,
            vote_count: 4218,
            character: 'Nervous Woman on Plane',
            credit_id: '5e2a0c1011386c00163e886d',
            order: 36,
          },
        },
      ],
      '2012': [
        {
          date: '2012-12-20',
          year: 2012,
          info: {
            adult: false,
            backdrop_path: '/botG6F4zvVD6WnDxQCWTU7U5cTD.jpg',
            genre_ids: [35],
            id: 89492,
            original_language: 'en',
            original_title: 'This Is 40',
            overview:
              'Após anos de casamento, Pete e Debbie estão chegando em uma fase de decadência. Enquanto tentam equilibrar romance, carreiras profissionais, pais e filhos, com seu próprio e hilariante, eles também tem que imaginar como aproveitar o resto de suas vidas.',
            popularity: 42.032,
            poster_path: '/j2Zt3IaAtRwHBIUrgArpXQzpOPP.jpg',
            release_date: '2012-12-20',
            title: 'Bem-Vindo aos 40',
            video: false,
            vote_average: 5.876,
            vote_count: 2089,
            character: 'Barb',
            credit_id: '52fe4a1c9251416c910c39a7',
            order: 12,
          },
        },
        {
          date: '2012-01-27',
          year: 2012,
          info: {
            adult: false,
            backdrop_path: '/jOBqJMTOlLZBMtNFnGZnfOt1qCW.jpg',
            genre_ids: [16, 10751, 12],
            id: 137200,
            original_language: 'en',
            original_title: 'Back To The Sea',
            overview:
              'Conta a história comovente da viagem para casa de um peixinho. Quando pequeno peixe Kevin é apanhado em uma rede e levado para um pequeno tanque de um restaurante de Nova York, ele tem que encontrar uma maneira de escapar e fazer o seu caminho de volta para casa para sua família ao mar que ele tanto ama. Junto com seus novos amigos e com a ajuda de um humano, filho do proprietário do restaurante, Kevin embarca na viagem de sua vida. Um filme com momentos hilários, como muita ação e emoção, que agrada toda a família.',
            popularity: 5.209,
            poster_path: '/96LsdX3rx9cSI8ESvVeosqUMK8S.jpg',
            release_date: '2012-01-27',
            title: 'De Volta ao Fundo do Mar',
            video: false,
            vote_average: 4.1,
            vote_count: 7,
            character: 'Danny (voice)',
            credit_id: '60021b32a9b9a4003d869b3f',
            order: 14,
          },
        },
      ],
      '2013': [
        {
          date: '2013-09-01',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/3q0l3yJmoOu9htpXB6GeAJ5xxJT.jpg',
            genre_ids: [10751, 16],
            id: 256051,
            original_language: 'en',
            original_title: 'Curious George: A Halloween Boo Fest',
            overview:
              'Uma Aventura de Halloween repleta de diversão! Prepare-se para a mais pura diversão com George, o Curioso em seu\r primeiro filme de Halloween.',
            popularity: 11.519,
            poster_path: '/2AQMICn0epi3FZ1SLP31JohlHPc.jpg',
            release_date: '2013-09-01',
            title: 'George, o Curioso e o dia das Bruxas',
            video: false,
            vote_average: 6.977,
            vote_count: 67,
            character: 'Bill (voice)',
            credit_id: '58182364c3a36837d9001882',
            order: 6,
          },
        },
        {
          date: '2013-08-30',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/1oVtSVOLWQszj5DE4n6fWH1Hz8a.jpg',
            genre_ids: [35, 18],
            id: 156708,
            original_language: 'en',
            original_title: 'Afternoon Delight',
            overview:
              'Uma dona de casa, com uma vida aparentemente idílica, coloca tudo em risco quando decide proteger uma stripper que conheceu com seu marido, empregando-a como babá por tempo integral para seus filhos, chocando seu marido e sua comunidade. A comédia de humor negro e sexy é dirigida por Jill Soloway e protagonizada por Josh Radnor, Kathryn Hahn e Jane Lynch.',
            popularity: 16.368,
            poster_path: '/vqPH9thiPqCXfmBdKHyAVxzZ81C.jpg',
            release_date: '2013-08-30',
            title: 'Desejos da Tarde',
            video: false,
            vote_average: 5.752,
            vote_count: 208,
            character: 'Amanda',
            credit_id: '52fe4bab9251416c910e1ef5',
            order: 4,
          },
        },
        {
          date: '2013-03-15',
          year: 2013,
          info: {
            adult: false,
            backdrop_path: '/xibuu1d7qu0xScU7ac2VNdUnXnz.jpg',
            genre_ids: [16, 10751],
            id: 270029,
            original_language: 'en',
            original_title: 'Curious George Swings Into Spring',
            overview: '',
            popularity: 10.639,
            poster_path: '/kh3aLGnQobkfVWcIQwhT1nJyF5M.jpg',
            release_date: '2013-03-15',
            title: 'George, o Curioso - Uma Aventura na Primavera',
            video: false,
            vote_average: 7.5,
            vote_count: 13,
            character: 'Bill/Sprint Quint',
            credit_id: '59da07d992514124cd03edd1',
            order: 8,
          },
        },
      ],
      '2016': [
        {
          date: '2016-07-28',
          year: 2016,
          info: {
            adult: false,
            backdrop_path: '/7lcwCb9DqQxffR5xdJZPOsxkxPL.jpg',
            genre_ids: [35],
            id: 376659,
            original_language: 'en',
            original_title: 'Bad Moms',
            overview:
              'Uma mulher (Mila Kunis), com vida aparentemente perfeita acaba ficando estressada além do ponto com as obrigações domésticas. Cansada da situação, ela se une a duas outras mulheres (Kathryn Hahn e Kristen Bell) que passam pelos mesmos problemas e juntas iniciam uma intensa jornada de libertação.',
            popularity: 37.916,
            poster_path: '/mbLhrGT6eci3mL6uPcnRqcVGWGN.jpg',
            release_date: '2016-07-28',
            title: 'Perfeita é a Mãe!',
            video: false,
            vote_average: 6.506,
            vote_count: 3979,
            character: 'Vicky',
            credit_id: '573278ecc3a3686a3600052d',
            order: 7,
          },
        },
        {
          date: '2016-04-07',
          year: 2016,
          info: {
            adult: false,
            backdrop_path: '/qAwXM5ZTA2tEYkLHTQyd1xFyH0g.jpg',
            genre_ids: [35],
            id: 323676,
            original_language: 'en',
            original_title: 'The Boss',
            overview:
              'Michelle Darnell (Melissa McCarthy) é uma poderosa industrial que é enviada para a cadeia após ser pega por traição, negociando informações confidenciais do mercado em troca de lucro. Quando ela volta pronta se reerguer como a queridinha dos Estados Unidos, nem todo mundo que foi enganado e prejudicado está pronto para perdoar e esquecer seus atos.',
            popularity: 26.702,
            poster_path: '/jEfzaXdgglZFIkJY7pmiEj1YufE.jpg',
            release_date: '2016-04-07',
            title: 'A Chefa',
            video: false,
            vote_average: 5.823,
            vote_count: 1285,
            character: 'Helen',
            credit_id: '56eb295c925141707d0006e9',
            order: 9,
          },
        },
      ],
      '2021': [
        {
          date: '2021-08-26',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/4t8T9NCte10R5CAXVhHDnmkPd3X.jpg',
            genre_ids: [35, 80],
            id: 628914,
            original_language: 'en',
            original_title: 'Queenpins',
            overview:
              'Connie e JoJo são donas de casa BFF no subúrbio de Phoenix, que tropeçam em um esquema para falsificar cupons e criar um cartel de US $ 40 milhões. Quando uma equipe da SWAT destrói seu esconderijo, eles encontram caixotes de rifles de assalto, carros esportivos de última geração e caixas de absorventes internos cheios de dinheiro.',
            popularity: 28.69,
            poster_path: '/ldo9MFJ2bmA5qKd4sbjUUzJUUa8.jpg',
            release_date: '2021-08-26',
            title: 'As Trambiqueiras',
            video: false,
            vote_average: 6.522,
            vote_count: 395,
            character: 'Crystal',
            credit_id: '5fcb795d11386c003ccf5814',
            order: 15,
          },
        },
        {
          date: '2021-03-29',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/mvxR0mbDVQkQp3K1OhEU9iDbGcA.jpg',
            genre_ids: [35],
            id: 595813,
            original_language: 'en',
            original_title: 'Barb & Star Go to Vista Del Mar',
            overview:
              'A história dos melhores amigos Barb e Star, que deixam sua pequena cidade do centro-oeste pela primeira vez para sair de férias em Vista Del Mar, Flórida, onde logo se encontram envolvidos em aventura, amor e um plano maligno de um vilão para matar todos na cidade.',
            popularity: 17.544,
            poster_path: '/6Z1a6RUMWGRHoecMPrV2VTAZNOL.jpg',
            release_date: '2021-03-29',
            title: 'Duas Tias Loucas de Férias',
            video: false,
            vote_average: 5.952,
            vote_count: 218,
            character: 'Barb',
            credit_id: '5cb7d7d4c3a3686b0784e882',
            order: 1,
          },
        },
        {
          date: '2021-03-18',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/zbOUAHIMR46DLLDYRM7AX8cY98I.jpg',
            genre_ids: [35, 10749, 18],
            id: 610290,
            original_language: 'en',
            original_title: 'Looks That Kill',
            overview:
              'Max Richards é um adolescente de dezesseis anos de idade forçado a viver com um rosto letalmente atraente. Tudo muda quando ele conhece Alex, uma garota com sua própria condição bizarra, que o ajuda numa jornada de auto-descobrimento... sem matar ninguém acidentalmente.',
            popularity: 19.753,
            poster_path: '/zhm9NhbSM57VpFxzX3cGFSyeGs7.jpg',
            release_date: '2021-03-18',
            title: 'Lindo de Morrer',
            video: false,
            vote_average: 7.083,
            vote_count: 156,
            character: 'Jan',
            credit_id: '5ee977231685da0037290c80',
            order: 3,
          },
        },
      ],
      '2022': [
        {
          date: '2022-09-16',
          year: 2022,
          info: {
            adult: false,
            backdrop_path: '/3xGfsAYAxVmYj1CbE5vAkmMJbHo.jpg',
            genre_ids: [35, 9648, 80],
            id: 724665,
            original_language: 'en',
            original_title: 'Confess, Fletch',
            overview:
              'O repórter investigativo I.M. Fletch envolve-se numa teia de assassinatos conectada ao mundo das obras de arte. Quando ele mesmo é considerado um dos suspeitos, precisa buscar respostas para provar a sua inocência. Baseado na série de livros de Gregory McDonald, é um reboot do personagem interpretado por Chevy Chase nos anos 1980.',
            popularity: 37.687,
            poster_path: '/vbi7lQ7tABBZb1z0TzpBEdEjUmn.jpg',
            release_date: '2022-09-16',
            title: 'Confesse, Fletch',
            video: false,
            vote_average: 6.254,
            vote_count: 242,
            character: 'Eve',
            credit_id: '6307cc4185090f0082680e4a',
            order: 7,
          },
        },
        {
          date: '2022-06-22',
          year: 2022,
          info: {
            adult: false,
            backdrop_path: '/4rf2EXd5D8YHtwTrWIzo5JmvxXc.jpg',
            genre_ids: [35],
            id: 1026686,
            original_language: 'en',
            original_title: 'The Hostage',
            overview: '',
            popularity: 4.626,
            poster_path: '/6q80K7tz4pSqHKU9Mk8DhIkDeIV.jpg',
            release_date: '2022-06-22',
            title: 'The Hostage',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Margot',
            credit_id: '632a4bc46af9dd00821a4bb3',
            order: 1,
          },
        },
      ],
      '2023': [
        {
          date: '2023-07-19',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
            genre_ids: [35, 12],
            id: 346698,
            original_language: 'en',
            original_title: 'Barbie',
            overview:
              'No mundo mágico das Barbies, "Barbieland", uma das bonecas começa a perceber que não se encaixa como as outras. Depois de ser expulsa, ela parte para uma aventura no "mundo real", onde descobre que a beleza está no interior de cada um.',
            popularity: 556.113,
            poster_path: '/yRRuLt7sMBEQkHsd1S3KaaofZn7.jpg',
            release_date: '2023-07-19',
            title: 'Barbie',
            video: false,
            vote_average: 7.1,
            vote_count: 8223,
            character: 'Anxiety Mom',
            credit_id: '64b796e7109cd0010183a8f4',
            order: 65,
          },
        },
        {
          date: '2023-06-22',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/fIQfdZ6fqf9mIbqBaexbgIEIk5K.jpg',
            genre_ids: [35],
            id: 864168,
            original_language: 'en',
            original_title: 'Joy Ride',
            overview:
              'Esta comédia acompanha quatro amigas asiáticas e seus processos de descoberta interior e da vida. Enquanto viajam para a Ásia a procura da mãe biológica de umas delas, elas enfrentam situações inusitadas e fortalecem ainda mais o laço entre elas.',
            popularity: 33.752,
            poster_path: '/kjFuCcTiTTmFbaNWIMcwrnZpMpr.jpg',
            release_date: '2023-06-22',
            title: 'Loucas em Apuros',
            video: false,
            vote_average: 6.811,
            vote_count: 301,
            character: 'Mary Sullivan',
            credit_id: '63e41307db154f007c3830cf',
            order: 5,
          },
        },
        {
          date: '2023-03-28',
          year: 2023,
          info: {
            adult: false,
            backdrop_path: '/AwB7HGeDTrBGkP2WEnNwg8Wa0E4.jpg',
            genre_ids: [9648, 35, 80],
            id: 638974,
            original_language: 'en',
            original_title: 'Murder Mystery 2',
            overview:
              'Depois de abrir uma agência de investigação, Nick e Audrey Spitz finalmente conseguem um caso importante: um amigo bilionário é sequestrado no dia de seu casamento.',
            popularity: 53.88,
            poster_path: '/pf1dQDb55mJ13KQMEYa4O0fni64.jpg',
            release_date: '2023-03-28',
            title: 'Mistério em Paris',
            video: false,
            vote_average: 6.444,
            vote_count: 1575,
            character: 'Mrs. Silverfox',
            credit_id: '61eefb18cedac400a0e263fa',
            order: 14,
          },
        },
      ],
      '2024': [
        {
          date: '2024-05-02',
          year: 2024,
          info: {
            adult: false,
            backdrop_path: '/sI6uCeF8mUlZx22mFfHSi9W3XQ9.jpg',
            genre_ids: [10749, 35, 18],
            id: 843527,
            original_language: 'en',
            original_title: 'The Idea of You',
            overview:
              'Solène, leva a filha, para assistir ao show de seu grupo favorito, August Moon. Lá, Solène se relaciona com um dos membros do grupo. Hayes Campbell é inteligente, atraente e confiante. A atração é imediata. O problema? É porque ele é vinte anos mais novo que Solène.',
            popularity: 1163.997,
            poster_path: '/5rIKVegF7XMPB02RaFaxtFwTPR0.jpg',
            release_date: '2024-05-02',
            title: 'Uma Ideia de Você',
            video: false,
            vote_average: 7.5,
            vote_count: 664,
            character: 'Tracy',
            credit_id: '65e76d6f6bdec301859b61b6',
            order: 3,
          },
        },
      ],
    },
  ],
  [
    'Production',
    {
      '2011': [
        {
          date: '2011-05-13',
          year: 2011,
          info: {
            adult: false,
            backdrop_path: '/i7ITE05sYhXl5yBT7dW6ythLSBI.jpg',
            genre_ids: [35, 10749],
            id: 55721,
            original_language: 'en',
            original_title: 'Bridesmaids',
            overview:
              'Lillian (Maya Rudolph) vai se casar e convida a amiga Annie (Kristen Wiig) para ser sua madrinha. Ela, que enfrenta problemas profissionais e amorosos, resolve se dedicar à função de corpo e alma. Só que, logo no primeiro evento organizado, Annie conhece Helen (Rose Byrne), uma bela e rica mulher que quer ser a nova melhor amiga de Lillian. As duas logo passam a disputar a proximidade da amiga, assim como o posto de organizadora do casamento e demais eventos pré-nupciais.',
            popularity: 54.695,
            poster_path: '/fy0uubz7JfImjvCODFHAoPVgSgy.jpg',
            release_date: '2011-05-13',
            title: 'Missão Madrinha de Casamento',
            video: false,
            vote_average: 6.529,
            vote_count: 4218,
            credit_id: '640f971eede1b00083fda3c5',
            department: 'Production',
            job: 'Co-Producer',
          },
        },
      ],
      '2015': [
        {
          date: '2015-12-24',
          year: 2015,
          info: {
            adult: false,
            backdrop_path: '/6VSss0C6xYmI7EteZIH9PkmsnF9.jpg',
            genre_ids: [18, 35],
            id: 274479,
            original_language: 'en',
            original_title: 'Joy',
            overview:
              'Joy é uma jovem mulher que constrói um império comercial e se torna uma matriarca. Os aliados se tornam adversários e os adversários se tornam aliados à medida que a vida interior de Joy e sua imaginação feroz a levam por um mundo de negócios voraz.',
            popularity: 40.475,
            poster_path: '/7icWz22RlPltHdIpR1iF95fuSrs.jpg',
            release_date: '2015-12-24',
            title: 'Joy: O Nome do Sucesso',
            video: false,
            vote_average: 6.529,
            vote_count: 3988,
            credit_id: '5677e6c092514179e100934a',
            department: 'Production',
            job: 'Executive Producer',
          },
        },
      ],
      '2021': [
        {
          date: '2021-03-29',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/mvxR0mbDVQkQp3K1OhEU9iDbGcA.jpg',
            genre_ids: [35],
            id: 595813,
            original_language: 'en',
            original_title: 'Barb & Star Go to Vista Del Mar',
            overview:
              'A história dos melhores amigos Barb e Star, que deixam sua pequena cidade do centro-oeste pela primeira vez para sair de férias em Vista Del Mar, Flórida, onde logo se encontram envolvidos em aventura, amor e um plano maligno de um vilão para matar todos na cidade.',
            popularity: 17.544,
            poster_path: '/6Z1a6RUMWGRHoecMPrV2VTAZNOL.jpg',
            release_date: '2021-03-29',
            title: 'Duas Tias Loucas de Férias',
            video: false,
            vote_average: 5.952,
            vote_count: 218,
            credit_id: '5cb7d9cdc3a3686b0b853839',
            department: 'Production',
            job: 'Producer',
          },
        },
      ],
    },
  ],
  [
    'Writing',
    {
      '2011': [
        {
          date: '2011-05-13',
          year: 2011,
          info: {
            adult: false,
            backdrop_path: '/i7ITE05sYhXl5yBT7dW6ythLSBI.jpg',
            genre_ids: [35, 10749],
            id: 55721,
            original_language: 'en',
            original_title: 'Bridesmaids',
            overview:
              'Lillian (Maya Rudolph) vai se casar e convida a amiga Annie (Kristen Wiig) para ser sua madrinha. Ela, que enfrenta problemas profissionais e amorosos, resolve se dedicar à função de corpo e alma. Só que, logo no primeiro evento organizado, Annie conhece Helen (Rose Byrne), uma bela e rica mulher que quer ser a nova melhor amiga de Lillian. As duas logo passam a disputar a proximidade da amiga, assim como o posto de organizadora do casamento e demais eventos pré-nupciais.',
            popularity: 54.695,
            poster_path: '/fy0uubz7JfImjvCODFHAoPVgSgy.jpg',
            release_date: '2011-05-13',
            title: 'Missão Madrinha de Casamento',
            video: false,
            vote_average: 6.529,
            vote_count: 4218,
            credit_id: '52fe48ddc3a36847f817d6cb',
            department: 'Writing',
            job: 'Screenplay',
          },
        },
      ],
      '2015': [
        {
          date: '2015-12-24',
          year: 2015,
          info: {
            adult: false,
            backdrop_path: '/6VSss0C6xYmI7EteZIH9PkmsnF9.jpg',
            genre_ids: [18, 35],
            id: 274479,
            original_language: 'en',
            original_title: 'Joy',
            overview:
              'Joy é uma jovem mulher que constrói um império comercial e se torna uma matriarca. Os aliados se tornam adversários e os adversários se tornam aliados à medida que a vida interior de Joy e sua imaginação feroz a levam por um mundo de negócios voraz.',
            popularity: 40.475,
            poster_path: '/7icWz22RlPltHdIpR1iF95fuSrs.jpg',
            release_date: '2015-12-24',
            title: 'Joy: O Nome do Sucesso',
            video: false,
            vote_average: 6.529,
            vote_count: 3988,
            credit_id: '5677e52992514179e10092fc',
            department: 'Writing',
            job: 'Story',
          },
        },
      ],
      '2017': [
        {
          date: '2017-06-09',
          year: 2017,
          info: {
            adult: false,
            backdrop_path: '/lrHfbfrEl9keXee7lLngtKtStS8.jpg',
            genre_ids: [18, 10752],
            id: 424488,
            original_language: 'en',
            original_title: 'Megan Leavey',
            overview:
              'Megan Leavey é uma especialista da marinha americana em treinamento de cães para detectar bombas. Ela é enviada ao Iraque, onde forma uma boa parceria com o cão Rex. Mas Megan é ferida e afastada do campo de batalha. Enquanto isso, o cão permanece em atividade, e ela espera a aposentadoria do animal para poder adotá-lo. Antes desse prazo, no entanto, a ex-militar descobre que o cachorro sofrerá uma eutanásia e luta para reverter a decisão.',
            popularity: 27.012,
            poster_path: '/ajZUEsDpo3EgiHZ8HX9yQJIRnFf.jpg',
            release_date: '2017-06-09',
            title: 'Megan Leavey',
            video: false,
            vote_average: 7.268,
            vote_count: 742,
            credit_id: '582205ec92514109b800014d',
            department: 'Writing',
            job: 'Writer',
          },
        },
      ],
      '2021': [
        {
          date: '2021-03-29',
          year: 2021,
          info: {
            adult: false,
            backdrop_path: '/mvxR0mbDVQkQp3K1OhEU9iDbGcA.jpg',
            genre_ids: [35],
            id: 595813,
            original_language: 'en',
            original_title: 'Barb & Star Go to Vista Del Mar',
            overview:
              'A história dos melhores amigos Barb e Star, que deixam sua pequena cidade do centro-oeste pela primeira vez para sair de férias em Vista Del Mar, Flórida, onde logo se encontram envolvidos em aventura, amor e um plano maligno de um vilão para matar todos na cidade.',
            popularity: 17.544,
            poster_path: '/6Z1a6RUMWGRHoecMPrV2VTAZNOL.jpg',
            release_date: '2021-03-29',
            title: 'Duas Tias Loucas de Férias',
            video: false,
            vote_average: 5.952,
            vote_count: 218,
            credit_id: '6027d81e397df00040da6602',
            department: 'Writing',
            job: 'Writer',
          },
        },
      ],
    },
  ],
]

describe('getListCredits', () => {
  it('deve retornar a lista de créditos formata por data', () => {
    const SUT = getListCredits([...MOCK_GET_PERSON_CREDITS.cast, ...MOCK_GET_PERSON_CREDITS.crew])
    const expected = MOCK_GET_PERSON_CREDITS_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('deve retornar undefined se não passar listCredit', () => {
    // @ts-expect-error
    const SUT1 = getListCredits(undefined)
    const expected1 = undefined
    expect(SUT1).toStrictEqual(expected1)

    // @ts-expect-error
    const SUT2 = getListCredits(null)
    const expected2 = undefined
    expect(SUT2).toStrictEqual(expected2)

    // @ts-expect-error
    const SUT3 = getListCredits('')
    const expected3 = undefined
    expect(SUT3).toStrictEqual(expected3)

    const SUT4 = getListCredits([])
    const expected4 = undefined
    expect(SUT4).toStrictEqual(expected4)
  })
})
