import { MOCK_GET_CREDITS_MOVIE, MOCK_GET_CREDITS_MOVIE_EMPTY_CAST, MOCK_GET_CREDITS_MOVIE_EMPTY_CREW } from '@/mocks'
import { describe, expect, it } from 'vitest'
import { crewList } from '.'

const MOCK_CREW_FORMATTED = [
  [
    'Art',
    [
      {
        adult: false,
        gender: 0,
        id: 4590987,
        known_for_department: 'Art',
        name: 'Jeanie Chang',
        original_name: 'Jeanie Chang',
        popularity: 0.923,
        profile_path: null,
        credit_id: '663581e066565a012614bb66',
        department: 'Art',
        job: 'Art Direction',
      },
      {
        adult: false,
        gender: 2,
        id: 2008159,
        known_for_department: 'Visual Effects',
        name: 'Pete Oswald',
        original_name: 'Pete Oswald',
        popularity: 5.59,
        profile_path: null,
        credit_id: '6635811799d5c3012957b72b',
        department: 'Art',
        job: 'Production Design',
      },
      {
        adult: false,
        gender: 2,
        id: 1653447,
        known_for_department: 'Art',
        name: 'Andrew Gaskill',
        original_name: 'Andrew Gaskill',
        popularity: 5.424,
        profile_path: null,
        credit_id: '5f75c04821621b0033319b71',
        department: 'Art',
        job: 'Storyboard Artist',
      },
      {
        adult: false,
        gender: 0,
        id: 2799121,
        known_for_department: 'Art',
        name: 'Julia Rodrigues',
        original_name: 'Julia Rodrigues',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5f75c080fea0d70035130bf6',
        department: 'Art',
        job: 'Storyboard Artist',
      },
    ],
  ],
  [
    'Crew',
    [
      {
        adult: false,
        gender: 2,
        id: 84417,
        known_for_department: 'Writing',
        name: 'Lee Eisenberg',
        original_name: 'Lee Eisenberg',
        popularity: 12.371,
        profile_path: '/qxA2eLl3AmBKfXqeCQy7RDlZSkE.jpg',
        credit_id: '6636f1186611b401246833b3',
        department: 'Crew',
        job: 'Additional Writing',
      },
      {
        adult: false,
        gender: 2,
        id: 84416,
        known_for_department: 'Writing',
        name: 'Gene Stupnitsky',
        original_name: 'Gene Stupnitsky',
        popularity: 13.848,
        profile_path: '/xAgtuSwjc8t7K4Z7AquN6a0wD0G.jpg',
        credit_id: '6636f12a83ee67012d41a00d',
        department: 'Crew',
        job: 'Additional Writing',
      },
      {
        adult: false,
        gender: 1,
        id: 4375809,
        known_for_department: 'Production',
        name: 'Michelle Smith',
        original_name: 'Michelle Smith',
        popularity: 1.049,
        profile_path: null,
        credit_id: '66358188af4324012554b398',
        department: 'Crew',
        job: 'Digital Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 2069474,
        known_for_department: 'Crew',
        name: 'Michael Hodges',
        original_name: 'Michael Hodges',
        popularity: 1.95,
        profile_path: null,
        credit_id: '663580c7470ead012811ee32',
        department: 'Crew',
        job: 'Executive Music Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 61417,
        known_for_department: 'Production',
        name: 'Randy Fullmer',
        original_name: 'Randy Fullmer',
        popularity: 5.691,
        profile_path: '/1jbvDdHduSFccaw2T9X6IhO1TkL.jpg',
        credit_id: '64afff04e24b935b30a2f007',
        department: 'Crew',
        job: 'In Memory Of',
      },
    ],
  ],
  [
    'Directing',
    [
      {
        adult: false,
        gender: 2,
        id: 61411,
        known_for_department: 'Writing',
        name: 'Mark Dindal',
        original_name: 'Mark Dindal',
        popularity: 13.752,
        profile_path: '/333OWiQBGLBjAWUemWySFzxCbhx.jpg',
        credit_id: '5f75bf1a29c626003975bab6',
        department: 'Directing',
        job: 'Director',
      },
    ],
  ],
  [
    'Editing',
    [
      {
        adult: false,
        gender: 0,
        id: 2799120,
        known_for_department: 'Editing',
        name: 'Mark Keefer',
        original_name: 'Mark Keefer',
        popularity: 0.771,
        profile_path: null,
        credit_id: '5f75c01e9a64350037a08c91',
        department: 'Editing',
        job: 'Editor',
      },
    ],
  ],
  [
    'Production',
    [
      {
        adult: false,
        gender: 1,
        id: 2325,
        known_for_department: 'Production',
        name: 'Monika Mikkelsen',
        original_name: 'Monika Mikkelsen',
        popularity: 5.578,
        profile_path: null,
        credit_id: '660aa40f35818f016238fe4f',
        department: 'Production',
        job: 'Casting',
      },
      {
        adult: false,
        gender: 0,
        id: 2551375,
        known_for_department: 'Production',
        name: 'Vanessa Choy',
        original_name: 'Vanessa Choy',
        popularity: 1.676,
        profile_path: null,
        credit_id: '66358097e92d830121d2d059',
        department: 'Production',
        job: 'Co-Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 65327,
        known_for_department: 'Production',
        name: 'Daniel Chuba',
        original_name: 'Daniel Chuba',
        popularity: 4.225,
        profile_path: null,
        credit_id: '6635809faf4324012b54ba86',
        department: 'Production',
        job: 'Co-Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 11,
        known_for_department: 'Writing',
        name: 'David Reynolds',
        original_name: 'David Reynolds',
        popularity: 17.063,
        profile_path: null,
        credit_id: '655233b99653f613f74cc2d9',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 1399695,
        known_for_department: 'Production',
        name: 'Carl Rogers',
        original_name: 'Carl Rogers',
        popularity: 1.586,
        profile_path: null,
        credit_id: '655233dbfd6fa101380b6150',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 1,
        id: 2551359,
        known_for_department: 'Production',
        name: 'Bridget McMeel',
        original_name: 'Bridget McMeel',
        popularity: 1.142,
        profile_path: null,
        credit_id: '5f75bfb79a64350038a1e930',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 56336,
        known_for_department: 'Writing',
        name: 'Jim Davis',
        original_name: 'Jim Davis',
        popularity: 9.766,
        profile_path: null,
        credit_id: '65523383fd6fa100ab972826',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 78875,
        known_for_department: 'Acting',
        name: 'Louis Koo',
        original_name: 'Louis Koo Tin Lok',
        popularity: 30.28,
        profile_path: '/yQuDBTzm7xWlJICNvl20OmcJP80.jpg',
        credit_id: '65523333ea84c71094fe96b9',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 2033026,
        known_for_department: 'Production',
        name: 'Scott Parish',
        original_name: 'Scott Parish',
        popularity: 3.042,
        profile_path: null,
        credit_id: '655233c967b61345cf03d38f',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 2588577,
        known_for_department: 'Directing',
        name: 'Simon Hedges',
        original_name: 'Simon Hedges',
        popularity: 3.255,
        profile_path: null,
        credit_id: '655233e89653f613f74cc2e9',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 4373765,
        known_for_department: 'Production',
        name: 'Chris Pflug',
        original_name: 'Chris Pflug',
        popularity: 0.6,
        profile_path: null,
        credit_id: '655234189653f613f3b6aceb',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 2819999,
        known_for_department: 'Production',
        name: 'Steve Sarowitz',
        original_name: 'Steve Sarowitz',
        popularity: 2.856,
        profile_path: null,
        credit_id: '65523422fd6fa101380b616a',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 2442799,
        known_for_department: 'Production',
        name: 'Peter Luo',
        original_name: 'Peter Luo',
        popularity: 1.898,
        profile_path: '/eMyQk45BLEmydQYV5z5Lh4APVSj.jpg',
        credit_id: '6552346d67b61345cb4c4529',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 88675,
        known_for_department: 'Acting',
        name: 'Justin Baldoni',
        original_name: 'Justin Baldoni',
        popularity: 13.207,
        profile_path: '/2sc6iUWljADnqtjsaKU3s6f0DGW.jpg',
        credit_id: '66358073c0442901298f38e7',
        department: 'Production',
        job: 'Executive Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 1011957,
        known_for_department: 'Production',
        name: 'John Cohen',
        original_name: 'John Cohen',
        popularity: 9.236,
        profile_path: '/2ItA4bGkHMC11Z7JSJAyPwALHXD.jpg',
        credit_id: '5f75bf6121621b003533f7af',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 956249,
        known_for_department: 'Production',
        name: 'Steven P. Wegner',
        original_name: 'Steven P. Wegner',
        popularity: 5.71,
        profile_path: null,
        credit_id: '5f75bfdb21621b0033319a82',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 47286,
        known_for_department: 'Production',
        name: 'Andrew A. Kosove',
        original_name: 'Andrew A. Kosove',
        popularity: 9.844,
        profile_path: null,
        credit_id: '62eaec251bf266005da4df76',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 47285,
        known_for_department: 'Production',
        name: 'Broderick Johnson',
        original_name: 'Broderick Johnson',
        popularity: 3.929,
        profile_path: '/lACnKu6Mxx5fGpWLt8qh0oevaQU.jpg',
        credit_id: '62eaec3448333a0061eb3699',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 3348438,
        known_for_department: 'Production',
        name: 'Namit Malhotra',
        original_name: 'Namit Malhotra',
        popularity: 2.929,
        profile_path: null,
        credit_id: '62eaec75e323f30060027200',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 2726507,
        known_for_department: 'Directing',
        name: 'Crosby Clyse',
        original_name: 'Crosby Clyse',
        popularity: 0.608,
        profile_path: null,
        credit_id: '6552339dd4fe0400fe047dc9',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 1395352,
        known_for_department: 'Production',
        name: 'Craig Sost',
        original_name: 'Craig Sost',
        popularity: 4.398,
        profile_path: null,
        credit_id: '65529a95ea84c7109225efd4',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 2,
        id: 1847420,
        known_for_department: 'Production',
        name: 'Tom Jacomb',
        original_name: 'Tom Jacomb',
        popularity: 2.142,
        profile_path: null,
        credit_id: '655341da9653f613f474953b',
        department: 'Production',
        job: 'Producer',
      },
      {
        adult: false,
        gender: 0,
        id: 1564995,
        known_for_department: 'Production',
        name: 'Mark Swenson',
        original_name: 'Mark Swenson',
        popularity: 1.988,
        profile_path: null,
        credit_id: '5f75c08dfea0d70035130c08',
        department: 'Production',
        job: 'Production Accountant',
      },
      {
        adult: false,
        gender: 1,
        id: 1450294,
        known_for_department: 'Production',
        name: 'Kristen Caplan',
        original_name: 'Kristen Caplan',
        popularity: 0.6,
        profile_path: null,
        credit_id: '5f75c03e9a64350037a08da4',
        department: 'Production',
        job: 'Production Manager',
      },
      {
        adult: false,
        gender: 1,
        id: 1819111,
        known_for_department: 'Production',
        name: 'Daniela Kriston',
        original_name: 'Daniela Kriston',
        popularity: 7.868,
        profile_path: null,
        credit_id: '64064c81b6cff100e7277879',
        department: 'Production',
        job: 'Researcher',
      },
    ],
  ],
  [
    'Sound',
    [
      {
        adult: false,
        gender: 2,
        id: 4500,
        known_for_department: 'Sound',
        name: 'John Debney',
        original_name: 'John Debney',
        popularity: 13.749,
        profile_path: '/iUwBpunUEdknzkRpgAyodwIEh4n.jpg',
        credit_id: '64afff1d6a3448010b732c3c',
        department: 'Sound',
        job: 'Original Music Composer',
      },
      {
        adult: false,
        gender: 2,
        id: 19767,
        known_for_department: 'Acting',
        name: 'Snoop Dogg',
        original_name: 'Snoop Dogg',
        popularity: 22.55,
        profile_path: '/rbxBK2m6fEq0oHeMoBUMVYkJEdJ.jpg',
        credit_id: '660ed7545aadc4014963500a',
        department: 'Sound',
        job: 'Songs',
      },
      {
        adult: false,
        gender: 2,
        id: 94357,
        known_for_department: 'Acting',
        name: 'Keith Urban',
        original_name: 'Keith Urban',
        popularity: 3.544,
        profile_path: '/6jB3gPO4yhdr24iqLjNS1Nw83SL.jpg',
        credit_id: '660ed75933a376017d845e59',
        department: 'Sound',
        job: 'Songs',
      },
      {
        adult: false,
        gender: 2,
        id: 2385063,
        known_for_department: 'Acting',
        name: 'Calum Scott',
        original_name: 'Calum Scott',
        popularity: 6.408,
        profile_path: '/edo73jg6JAovDClAmuFL7zkIBt.jpg',
        credit_id: '6635e1526611b4012467bb17',
        department: 'Sound',
        job: 'Songs',
      },
      {
        adult: false,
        gender: 2,
        id: 1513968,
        known_for_department: 'Sound',
        name: 'Jon Batiste',
        original_name: 'Jon Batiste',
        popularity: 10.596,
        profile_path: '/bdRHptdxbY8gMCAiJ48kdLB8Vzy.jpg',
        credit_id: '663be29747a808a718a8e2aa',
        department: 'Sound',
        job: 'Songs',
      },
      {
        adult: false,
        gender: 0,
        id: 1776299,
        known_for_department: 'Sound',
        name: 'Luke Gentry',
        original_name: 'Luke Gentry',
        popularity: 2.033,
        profile_path: null,
        credit_id: '659b66748741c40258949889',
        department: 'Sound',
        job: 'Sound Designer',
      },
      {
        adult: false,
        gender: 2,
        id: 1392609,
        known_for_department: 'Sound',
        name: 'Chris Burdon',
        original_name: 'Chris Burdon',
        popularity: 8.324,
        profile_path: null,
        credit_id: '659b66cba1074b0258f9a79f',
        department: 'Sound',
        job: 'Sound Re-Recording Mixer',
      },
      {
        adult: false,
        gender: 0,
        id: 1349056,
        known_for_department: 'Sound',
        name: 'Johnathan Rush',
        original_name: 'Johnathan Rush',
        popularity: 3.262,
        profile_path: null,
        credit_id: '659b66f5bd588b20998d00d7',
        department: 'Sound',
        job: 'Sound Re-Recording Mixer',
      },
      {
        adult: false,
        gender: 2,
        id: 1393303,
        known_for_department: 'Sound',
        name: 'Jeremy Price',
        original_name: 'Jeremy Price',
        popularity: 1.348,
        profile_path: null,
        credit_id: '659b66411d1bf400f3a0612e',
        department: 'Sound',
        job: 'Supervising Sound Editor',
      },
      {
        adult: false,
        gender: 2,
        id: 1373711,
        known_for_department: 'Sound',
        name: 'Ben Meechan',
        original_name: 'Ben Meechan',
        popularity: 2.601,
        profile_path: null,
        credit_id: '659b66908741c400ef30d3a5',
        department: 'Sound',
        job: 'Supervising Sound Editor',
      },
    ],
  ],
  [
    'Visual Effects',
    [
      {
        adult: false,
        gender: 2,
        id: 1408648,
        known_for_department: 'Visual Effects',
        name: 'Jason Boose',
        original_name: 'Jason Boose',
        popularity: 1.151,
        profile_path: null,
        credit_id: '655341e89653f613f74d6c68',
        department: 'Visual Effects',
        job: 'Animation Director',
      },
      {
        adult: false,
        gender: 2,
        id: 2616360,
        known_for_department: 'Visual Effects',
        name: 'Taylor Krahenbuhl',
        original_name: 'Taylor Krahenbuhl',
        popularity: 1.4,
        profile_path: null,
        credit_id: '663585e2c0442901238f524d',
        department: 'Visual Effects',
        job: 'Character Designer',
      },
      {
        adult: false,
        gender: 2,
        id: 4375782,
        known_for_department: 'Visual Effects',
        name: 'Freddy Chaleur',
        original_name: 'Freddy Chaleur',
        popularity: 0.61,
        profile_path: null,
        credit_id: '655341f70816c7011a0accbc',
        department: 'Visual Effects',
        job: 'Visual Effects Supervisor',
      },
    ],
  ],
  [
    'Writing',
    [
      {
        adult: false,
        gender: 0,
        id: 1705227,
        known_for_department: 'Writing',
        name: 'Mark Torgove',
        original_name: 'Mark Torgove',
        popularity: 6.006,
        profile_path: null,
        credit_id: '65529a53903c5200e1ef381c',
        department: 'Writing',
        job: 'Screenplay',
      },
      {
        adult: false,
        gender: 2,
        id: 4174087,
        known_for_department: 'Writing',
        name: 'Paul A. Kaplan',
        original_name: 'Paul A. Kaplan',
        popularity: 3.445,
        profile_path: null,
        credit_id: '65529a61ea84c71094febdc6',
        department: 'Writing',
        job: 'Screenplay',
      },
    ],
  ],
]

describe('formatCrewList', () => {
  it('deve retornar crewList sem duplicatas e formatada', () => {
    const SUT = crewList({ credits: MOCK_GET_CREDITS_MOVIE })
    const expected = MOCK_CREW_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('deve retornar crewList sem duplicatas ao passar credits sem cast', () => {
    const SUT = crewList({ credits: MOCK_GET_CREDITS_MOVIE_EMPTY_CAST })
    const expected = MOCK_CREW_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('deve retornar undefined ao não passar credits', () => {
    // @ts-expect-error
    const SUT1 = crewList({ credits: undefined })
    const expected1 = undefined
    expect(SUT1).toBe(expected1)

    // @ts-expect-error
    const SUT2 = crewList({ credits: null })
    const expected2 = undefined
    expect(SUT2).toBe(expected2)

    // @ts-expect-error
    const SUT3 = crewList({ credits: '' })
    const expected3 = undefined
    expect(SUT3).toBe(expected3)
  })

  it('deve retornar undefined ao passar credits sem crew ou crew sem conteúdo', () => {
    const { crew: _, ...mock } = MOCK_GET_CREDITS_MOVIE_EMPTY_CREW
    // @ts-expect-error
    const SUT1 = crewList({ credits: mock })
    const expected1 = undefined
    expect(SUT1).toBe(expected1)

    const SUT2 = crewList({ credits: MOCK_GET_CREDITS_MOVIE_EMPTY_CREW })
    const expected2 = undefined
    expect(SUT2).toBe(expected2)
  })
})
