import { MOCK_GET_CLASSIFICATIONS, MOCK_GET_UPCOMING_PAGE_1, MOCK_GET_VIDEOS, MOCK_GET_WATCH } from '@/mocks'
import { describe, expect, it } from 'vitest'
import {
  filterClassificationsByRegion,
  filterWatchWithInfos,
  removeMovieWithoutInfos,
  removeMovieWithoutThumbnail,
  removeVideosAreNotYouTube,
  sortByReleaseDateAsc,
  sortByReleaseDateDesc,
} from '.'

const MOCK_SORT_BY_RELEASE_DATE_ASC_FORMATTED = [
  {
    adult: false,
    backdrop_path: '/q8IEFmEGGSGmAWfwRs23XDwdFN4.jpg',
    genre_ids: [878, 28, 12],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'Quando o mundo entra em colapso, a jovem Furiosa é sequestrada do Green Place das Muitas Mães e cai nas mãos da horda de motoqueiros liderada pelo Senhor da Guerra Dementus. Vagando pelo deserto condenado, eles encontram a Cidadela controlada por Immortan Joe. Enquanto os dois tiranos lutam por poder e controle, Furiosa terá que sobreviver a muitos desafios para encontrar e trilhar o caminho de volta para casa.',
    popularity: 434.408,
    poster_path: '/afy34b5II1NgA6paGgHnf4y86w1.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Furiosa: Uma Saga Mad Max',
    video: false,
    vote_average: 8.2,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
    genre_ids: [28, 53],
    id: 560016,
    original_language: 'en',
    original_title: 'Monkey Man',
    overview:
      'Kid é um jovem que ganha a vida em um clube de luta clandestino, onde, usando uma máscara de gorila, é brutalmente espancado todas as noites por lutadores mais populares. Após anos de raiva contida e uma vida muito dura, Kid encontra uma maneira de se infiltrar na elite da cidade. À medida que seu trauma de infância ressurge, ele não mede esforços para acertar as contas com os homens da alta sociedade que tiraram o pouco que ele tinha.',
    popularity: 224.9,
    poster_path: '/ziXIsqVTBrKajZpVEGKiSvot3gu.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Fúria Primitiva',
    video: false,
    vote_average: 7.2,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/9umudqXenMm3kfX7hCTekIH0XWm.jpg',
    genre_ids: [10749, 35, 18],
    id: 891933,
    original_language: 'en',
    original_title: 'Sometimes I Think About Dying',
    overview:
      'Fran gosta de pensar em morrer. Quando ela faz rir um cara no escritório, ele quer mais - um encontro no cinema, uma fatia de torta, uma conversa. Mas se namorar com ele significa aprender a viver, ela tem certeza de que não pode fazer isso.',
    popularity: 18.61,
    poster_path: '/vpcjCTzVoxoxIBmBGpjGrWL4JIV.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Sometimes I Think About Dying',
    video: false,
    vote_average: 6.1,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/PMu7kiBY9OcdXlebOvtYS7E0m9.jpg',
    genre_ids: [35, 10749],
    id: 1184420,
    original_language: 'pt',
    original_title: 'Morando com o Crush',
    overview:
      'Luana e Hugo são colegas de escola e apaixonados um pelo outro. Mas quando a mãe de Hugo e o pai de Luana decidem namorar e mudar de cidade com todos, a situação complica para os pretendentes.',
    popularity: 7.899,
    poster_path: '/eZA7H3FN20qX5ppoCsdUsMSvYk4.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Morando com o Crush',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/4Q3Y3Q1jKMxGrskORNnZlwOTajG.jpg',
    genre_ids: [18],
    id: 1008795,
    original_language: 'pt',
    original_title: 'A Festa de Léo',
    overview:
      'A história retrata a realidade de uma família da favela do Vidigal e se passa nos dias que antecedem a festa de 12 anos de Léo, filho da batalhadora Rita. Ela não mede esforços para fazer uma grande comemoração para o menino, mas, no dia do evento, descobre que o marido, Dudu, envolvido com drogas, roubou todo o dinheiro destinado à festa.  A partir daí, a protagonista vai precisar superar vários obstáculos para resolver o problema e, para isso, terá que contar com a compreensão do garoto e com uma grande rede de apoio dos amigos.',
    popularity: 7.581,
    poster_path: '/M9mKw9YVssnrf04tOj67UPDYBQ.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - A Festa de Léo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [37, 35],
    id: 1292135,
    original_language: 'pt',
    original_title: 'Ao Meio Dia Levarei Sua Cabeça',
    overview: 'John Reeves do Cavalo Vermelho tem sua vida ameaçada quando um de seus rivais tenta ganhar a sua cabeça',
    popularity: 1.4,
    poster_path: '/svFdpPrStafCnCEo1JDojvZ7Hl3.jpg',
    release_date: '2024-05-25',
    title: 'MOCK PAGE 1 BREVE - Ao Meio Dia Levarei Sua Cabeça',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: 'en',
    original_title: 'Immaculate',
    overview:
      'Cecilia, uma jovem religiosa, se torna freira em um convento isolado na região rural italiana. Após uma gravidez misteriosa, Cecilia é atormentada por forças perversas, enquanto confronta segredos sombrios e horrores do convento.',
    popularity: 596.447,
    poster_path: '/tsV19P8J4NMP54cC8QCg1IkLLks.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Imaculada',
    video: false,
    vote_average: 6.188,
    vote_count: 463,
  },
  {
    adult: false,
    backdrop_path: '/6LksoR7reQ45gQRik0zhrHmcpZw.jpg',
    genre_ids: [27, 53],
    id: 1010600,
    original_language: 'en',
    original_title: 'The Strangers: Chapter 1',
    overview:
      'Uma jovem viaja para o campo com seu namorado para começar uma nova vida. Quando seu carro quebra, o casal é forçado a passar a noite em uma isolada casa Airbnb, onde a dupla é aterrorizada até o amanhecer por três estranhos mascarados.',
    popularity: 124.438,
    poster_path: '/kiFxBuX0yQTw042MeqCuTZypfYD.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Os Estranhos: Capítulo 1',
    video: false,
    vote_average: 4.65,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: '/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg',
    genre_ids: [16, 18],
    id: 1012201,
    original_language: 'ja',
    original_title: '劇場版ハイキュー!! ゴミ捨て場の決戦',
    overview:
      'Shoyo Hinata se junta ao clube de vôlei do Karasuno High para ser como seu ídolo, um ex-jogador do Karasuno conhecido como o “Pequeno Gigante”. Mas Hinata logo descobre que deve se juntar a seu inimigo do ensino médio, Tobio Kageyama. Seus estilos conflitantes se transformam em uma arma surpreendente, mas será que eles conseguirão derrotar seu rival Nekoma High na tão aguardada “Dumpster Battle”, o tão aguardado confronto final entre duas equipes adversárias?',
    popularity: 87.883,
    poster_path: '/8iPstBjKGHEQcart2JaeJoD64Ht.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - HAIKYU!! A Batalha do Lixo',
    video: false,
    vote_average: 8.7,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/rBo0yYQTruIYEuXdyCAyVVlNb2H.jpg',
    genre_ids: [18],
    id: 974036,
    original_language: 'en',
    original_title: 'Ordinary Angels',
    overview:
      'Inspirado na incrível história real de uma cabeleireira de Louisville, Kentucky, que sozinha, reuniu  uma comunidade inteira para ajudar um pai viúvo a salvar a vida de sua filha de 5 anos gravemente doente, após sua cidade ter sido atingida por uma grande nevasca causada pela onda de frio norte-americana de 1994.',
    popularity: 87.435,
    poster_path: '/7pe1dn5RPxpkEOfOZtXRZAehxv3.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Anjos na Terra',
    video: false,
    vote_average: 7.91,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27, 53],
    id: 1066383,
    original_language: 'en',
    original_title: 'AMP House',
    overview: '',
    popularity: 4.862,
    poster_path: null,
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - AMP House',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/eDJgcItr9MQm72KjSJkq7rX9SIW.jpg',
    genre_ids: [35, 10402, 10749],
    id: 782718,
    original_language: 'pt',
    original_title: 'Meu Sangue Ferve por Você',
    overview:
      'Em 1979, Magal, um dos artistas mais populares e celebrados do país, segue a rotina de ensaios e compromissos em Salvador. Durante um programa de TV, conhece a deslumbrante Magali e é acometido por uma paixão inédita e avassaladora. Para conquistá-la, precisará vencer a resistência de Jean Pierre, seu empresário passional, além da desconfiança da família, dos amigos e da própria amada.',
    popularity: 3.212,
    poster_path: '/7PrQWs7z5ASojTQRWOilIzm1smr.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Meu Sangue Ferve por Você',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10749],
    id: 1220221,
    original_language: 'pt',
    original_title: 'Quarta de Amalá',
    overview:
      'Na manhã de uma quarta-feira, Suiá e Rai embarcam na jornada de preparar o Amalá para Pai Sàngó. Depois de rodar o Amalá, seguem pra casa juntas. Chegando em casa, um beijo apaixonado desencadeia inseguranças em Rai que abalam Suiá. Na manhã seguinte, Rai volta determinada a ajeitar as coisas.',
    popularity: 2.73,
    poster_path: '/xeWtDoJfsqKvCSZeQpQv3Wdozt9.jpg',
    release_date: '2024-05-31',
    title: 'MOCK PAGE 1 BREVE - Quarta de Amalá',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/vvf5frN4sBN2JzBzNedNdbCwLOu.jpg',
    genre_ids: [16, 18, 14],
    id: 1013578,
    original_language: 'pt',
    original_title: 'Dia Zero',
    overview:
      'Durante um dia chuvoso, um homem, que vive na região central de uma cidade grande, tem um dia complicado, além de se ver cada vez mais distante da realidade.',
    popularity: 1.787,
    poster_path: '/9l1RIZZHfvruMA5SqAWAAyAuXny.jpg',
    release_date: '2024-06-01',
    title: 'MOCK PAGE 1 BREVE - Dia Zero',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1291272,
    original_language: 'pt',
    original_title: 'Laços',
    overview: '',
    popularity: 2.041,
    poster_path: null,
    release_date: '2024-06-03',
    title: 'MOCK PAGE 1 BREVE - Laços',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg',
    genre_ids: [27, 9648, 53],
    id: 1086747,
    original_language: 'en',
    original_title: 'The Watchers',
    overview:
      'Mina, uma artista de 28 anos, que se perde em uma imensa e assustadora floresta natural no oeste da Irlanda. Quando Mina finalmente encontra abrigo, ela acaba presa ao lado de três estranhos que são vigiados e perseguidos por criaturas misteriosas todas as noites.',
    popularity: 43.443,
    poster_path: '/jFpsKOCppRvwP0Igwp0F0Xu1RBJ.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Os Observadores',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/bgPkOllkc6tSLPTGSySm9hetMFs.jpg',
    genre_ids: [18, 80],
    id: 1097175,
    original_language: 'pt',
    original_title: 'Grande Sertão',
    overview:
      'A luta entre policiais e bandidos assumiu ares de uma guerra de verdade: a comunidade é cercada por um enorme muro, helicópteros rondam os céus, batalhões desfilam pelas ruas, os bandidos possuem um verdadeiro exército de guerreiros. Tudo isso se passa na gigantesca periferia urbana chamada de "Grande Sertão". O filme é uma adaptação do clássico literário homônimo de Guimarães Rosa.',
    popularity: 3.617,
    poster_path: '/eG2mub8IdF6JdxuW95FTav7eNTs.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Grande Sertão',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/JtN7Q03S3oq7A4KZ7Z3I7m3osP.jpg',
    genre_ids: [28, 53, 80],
    id: 573435,
    original_language: 'en',
    original_title: 'Bad Boys: Ride or Die',
    overview:
      'Os Bad Boys preferidos do mundo todo estão de volta com a mistura icônica de ação eletrizante e comédia escrachada, mas, dessa vez, com uma virada: os melhores de Miami são agora os mais procurados.',
    popularity: 114.211,
    poster_path: '/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Bad Boys: Até o Fim',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10749, 53],
    id: 1216571,
    original_language: 'en',
    original_title: 'June et John',
    overview: '',
    popularity: 5.24,
    poster_path: null,
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - June et John',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/z8tvRmo7LvV8P5T9R2GhtUc4MVL.jpg',
    genre_ids: [35],
    id: 1172335,
    original_language: 'pt',
    original_title: 'Mallandro: O Errado que Deu Certo',
    overview:
      'Mallandro perde uma competição de reality show. Incapaz de se deixar abater, Mallandro tenta conseguir novos trabalhos, sempre recorrendo aos seus bordões inimitáveis: rá!,iéié e glu-glu.',
    popularity: 4.433,
    poster_path: '/tIBSze3aeYf2c7l5sca6E3H1hUW.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Mallandro: O Errado que Deu Certo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
]

const MOCK_SORT_BY_RELEASE_DATE_DESC_FORMATTED = [
  {
    adult: false,
    backdrop_path: '/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg',
    genre_ids: [27, 9648, 53],
    id: 1086747,
    original_language: 'en',
    original_title: 'The Watchers',
    overview:
      'Mina, uma artista de 28 anos, que se perde em uma imensa e assustadora floresta natural no oeste da Irlanda. Quando Mina finalmente encontra abrigo, ela acaba presa ao lado de três estranhos que são vigiados e perseguidos por criaturas misteriosas todas as noites.',
    popularity: 43.443,
    poster_path: '/jFpsKOCppRvwP0Igwp0F0Xu1RBJ.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Os Observadores',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/bgPkOllkc6tSLPTGSySm9hetMFs.jpg',
    genre_ids: [18, 80],
    id: 1097175,
    original_language: 'pt',
    original_title: 'Grande Sertão',
    overview:
      'A luta entre policiais e bandidos assumiu ares de uma guerra de verdade: a comunidade é cercada por um enorme muro, helicópteros rondam os céus, batalhões desfilam pelas ruas, os bandidos possuem um verdadeiro exército de guerreiros. Tudo isso se passa na gigantesca periferia urbana chamada de "Grande Sertão". O filme é uma adaptação do clássico literário homônimo de Guimarães Rosa.',
    popularity: 3.617,
    poster_path: '/eG2mub8IdF6JdxuW95FTav7eNTs.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Grande Sertão',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/JtN7Q03S3oq7A4KZ7Z3I7m3osP.jpg',
    genre_ids: [28, 53, 80],
    id: 573435,
    original_language: 'en',
    original_title: 'Bad Boys: Ride or Die',
    overview:
      'Os Bad Boys preferidos do mundo todo estão de volta com a mistura icônica de ação eletrizante e comédia escrachada, mas, dessa vez, com uma virada: os melhores de Miami são agora os mais procurados.',
    popularity: 114.211,
    poster_path: '/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Bad Boys: Até o Fim',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10749, 53],
    id: 1216571,
    original_language: 'en',
    original_title: 'June et John',
    overview: '',
    popularity: 5.24,
    poster_path: null,
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - June et John',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/z8tvRmo7LvV8P5T9R2GhtUc4MVL.jpg',
    genre_ids: [35],
    id: 1172335,
    original_language: 'pt',
    original_title: 'Mallandro: O Errado que Deu Certo',
    overview:
      'Mallandro perde uma competição de reality show. Incapaz de se deixar abater, Mallandro tenta conseguir novos trabalhos, sempre recorrendo aos seus bordões inimitáveis: rá!,iéié e glu-glu.',
    popularity: 4.433,
    poster_path: '/tIBSze3aeYf2c7l5sca6E3H1hUW.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Mallandro: O Errado que Deu Certo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1291272,
    original_language: 'pt',
    original_title: 'Laços',
    overview: '',
    popularity: 2.041,
    poster_path: null,
    release_date: '2024-06-03',
    title: 'MOCK PAGE 1 BREVE - Laços',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/vvf5frN4sBN2JzBzNedNdbCwLOu.jpg',
    genre_ids: [16, 18, 14],
    id: 1013578,
    original_language: 'pt',
    original_title: 'Dia Zero',
    overview:
      'Durante um dia chuvoso, um homem, que vive na região central de uma cidade grande, tem um dia complicado, além de se ver cada vez mais distante da realidade.',
    popularity: 1.787,
    poster_path: '/9l1RIZZHfvruMA5SqAWAAyAuXny.jpg',
    release_date: '2024-06-01',
    title: 'MOCK PAGE 1 BREVE - Dia Zero',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10749],
    id: 1220221,
    original_language: 'pt',
    original_title: 'Quarta de Amalá',
    overview:
      'Na manhã de uma quarta-feira, Suiá e Rai embarcam na jornada de preparar o Amalá para Pai Sàngó. Depois de rodar o Amalá, seguem pra casa juntas. Chegando em casa, um beijo apaixonado desencadeia inseguranças em Rai que abalam Suiá. Na manhã seguinte, Rai volta determinada a ajeitar as coisas.',
    popularity: 2.73,
    poster_path: '/xeWtDoJfsqKvCSZeQpQv3Wdozt9.jpg',
    release_date: '2024-05-31',
    title: 'MOCK PAGE 1 BREVE - Quarta de Amalá',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: 'en',
    original_title: 'Immaculate',
    overview:
      'Cecilia, uma jovem religiosa, se torna freira em um convento isolado na região rural italiana. Após uma gravidez misteriosa, Cecilia é atormentada por forças perversas, enquanto confronta segredos sombrios e horrores do convento.',
    popularity: 596.447,
    poster_path: '/tsV19P8J4NMP54cC8QCg1IkLLks.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Imaculada',
    video: false,
    vote_average: 6.188,
    vote_count: 463,
  },
  {
    adult: false,
    backdrop_path: '/6LksoR7reQ45gQRik0zhrHmcpZw.jpg',
    genre_ids: [27, 53],
    id: 1010600,
    original_language: 'en',
    original_title: 'The Strangers: Chapter 1',
    overview:
      'Uma jovem viaja para o campo com seu namorado para começar uma nova vida. Quando seu carro quebra, o casal é forçado a passar a noite em uma isolada casa Airbnb, onde a dupla é aterrorizada até o amanhecer por três estranhos mascarados.',
    popularity: 124.438,
    poster_path: '/kiFxBuX0yQTw042MeqCuTZypfYD.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Os Estranhos: Capítulo 1',
    video: false,
    vote_average: 4.65,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: '/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg',
    genre_ids: [16, 18],
    id: 1012201,
    original_language: 'ja',
    original_title: '劇場版ハイキュー!! ゴミ捨て場の決戦',
    overview:
      'Shoyo Hinata se junta ao clube de vôlei do Karasuno High para ser como seu ídolo, um ex-jogador do Karasuno conhecido como o “Pequeno Gigante”. Mas Hinata logo descobre que deve se juntar a seu inimigo do ensino médio, Tobio Kageyama. Seus estilos conflitantes se transformam em uma arma surpreendente, mas será que eles conseguirão derrotar seu rival Nekoma High na tão aguardada “Dumpster Battle”, o tão aguardado confronto final entre duas equipes adversárias?',
    popularity: 87.883,
    poster_path: '/8iPstBjKGHEQcart2JaeJoD64Ht.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - HAIKYU!! A Batalha do Lixo',
    video: false,
    vote_average: 8.7,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/rBo0yYQTruIYEuXdyCAyVVlNb2H.jpg',
    genre_ids: [18],
    id: 974036,
    original_language: 'en',
    original_title: 'Ordinary Angels',
    overview:
      'Inspirado na incrível história real de uma cabeleireira de Louisville, Kentucky, que sozinha, reuniu  uma comunidade inteira para ajudar um pai viúvo a salvar a vida de sua filha de 5 anos gravemente doente, após sua cidade ter sido atingida por uma grande nevasca causada pela onda de frio norte-americana de 1994.',
    popularity: 87.435,
    poster_path: '/7pe1dn5RPxpkEOfOZtXRZAehxv3.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Anjos na Terra',
    video: false,
    vote_average: 7.91,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27, 53],
    id: 1066383,
    original_language: 'en',
    original_title: 'AMP House',
    overview: '',
    popularity: 4.862,
    poster_path: null,
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - AMP House',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/eDJgcItr9MQm72KjSJkq7rX9SIW.jpg',
    genre_ids: [35, 10402, 10749],
    id: 782718,
    original_language: 'pt',
    original_title: 'Meu Sangue Ferve por Você',
    overview:
      'Em 1979, Magal, um dos artistas mais populares e celebrados do país, segue a rotina de ensaios e compromissos em Salvador. Durante um programa de TV, conhece a deslumbrante Magali e é acometido por uma paixão inédita e avassaladora. Para conquistá-la, precisará vencer a resistência de Jean Pierre, seu empresário passional, além da desconfiança da família, dos amigos e da própria amada.',
    popularity: 3.212,
    poster_path: '/7PrQWs7z5ASojTQRWOilIzm1smr.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Meu Sangue Ferve por Você',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [37, 35],
    id: 1292135,
    original_language: 'pt',
    original_title: 'Ao Meio Dia Levarei Sua Cabeça',
    overview: 'John Reeves do Cavalo Vermelho tem sua vida ameaçada quando um de seus rivais tenta ganhar a sua cabeça',
    popularity: 1.4,
    poster_path: '/svFdpPrStafCnCEo1JDojvZ7Hl3.jpg',
    release_date: '2024-05-25',
    title: 'MOCK PAGE 1 BREVE - Ao Meio Dia Levarei Sua Cabeça',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/q8IEFmEGGSGmAWfwRs23XDwdFN4.jpg',
    genre_ids: [878, 28, 12],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'Quando o mundo entra em colapso, a jovem Furiosa é sequestrada do Green Place das Muitas Mães e cai nas mãos da horda de motoqueiros liderada pelo Senhor da Guerra Dementus. Vagando pelo deserto condenado, eles encontram a Cidadela controlada por Immortan Joe. Enquanto os dois tiranos lutam por poder e controle, Furiosa terá que sobreviver a muitos desafios para encontrar e trilhar o caminho de volta para casa.',
    popularity: 434.408,
    poster_path: '/afy34b5II1NgA6paGgHnf4y86w1.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Furiosa: Uma Saga Mad Max',
    video: false,
    vote_average: 8.2,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
    genre_ids: [28, 53],
    id: 560016,
    original_language: 'en',
    original_title: 'Monkey Man',
    overview:
      'Kid é um jovem que ganha a vida em um clube de luta clandestino, onde, usando uma máscara de gorila, é brutalmente espancado todas as noites por lutadores mais populares. Após anos de raiva contida e uma vida muito dura, Kid encontra uma maneira de se infiltrar na elite da cidade. À medida que seu trauma de infância ressurge, ele não mede esforços para acertar as contas com os homens da alta sociedade que tiraram o pouco que ele tinha.',
    popularity: 224.9,
    poster_path: '/ziXIsqVTBrKajZpVEGKiSvot3gu.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Fúria Primitiva',
    video: false,
    vote_average: 7.2,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/9umudqXenMm3kfX7hCTekIH0XWm.jpg',
    genre_ids: [10749, 35, 18],
    id: 891933,
    original_language: 'en',
    original_title: 'Sometimes I Think About Dying',
    overview:
      'Fran gosta de pensar em morrer. Quando ela faz rir um cara no escritório, ele quer mais - um encontro no cinema, uma fatia de torta, uma conversa. Mas se namorar com ele significa aprender a viver, ela tem certeza de que não pode fazer isso.',
    popularity: 18.61,
    poster_path: '/vpcjCTzVoxoxIBmBGpjGrWL4JIV.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Sometimes I Think About Dying',
    video: false,
    vote_average: 6.1,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/PMu7kiBY9OcdXlebOvtYS7E0m9.jpg',
    genre_ids: [35, 10749],
    id: 1184420,
    original_language: 'pt',
    original_title: 'Morando com o Crush',
    overview:
      'Luana e Hugo são colegas de escola e apaixonados um pelo outro. Mas quando a mãe de Hugo e o pai de Luana decidem namorar e mudar de cidade com todos, a situação complica para os pretendentes.',
    popularity: 7.899,
    poster_path: '/eZA7H3FN20qX5ppoCsdUsMSvYk4.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Morando com o Crush',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/4Q3Y3Q1jKMxGrskORNnZlwOTajG.jpg',
    genre_ids: [18],
    id: 1008795,
    original_language: 'pt',
    original_title: 'A Festa de Léo',
    overview:
      'A história retrata a realidade de uma família da favela do Vidigal e se passa nos dias que antecedem a festa de 12 anos de Léo, filho da batalhadora Rita. Ela não mede esforços para fazer uma grande comemoração para o menino, mas, no dia do evento, descobre que o marido, Dudu, envolvido com drogas, roubou todo o dinheiro destinado à festa.  A partir daí, a protagonista vai precisar superar vários obstáculos para resolver o problema e, para isso, terá que contar com a compreensão do garoto e com uma grande rede de apoio dos amigos.',
    popularity: 7.581,
    poster_path: '/M9mKw9YVssnrf04tOj67UPDYBQ.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - A Festa de Léo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
]

const MOCK_REMOVE_MOVIE_WITHOUT_THUMBNAIL_FORMATTED = [
  {
    adult: false,
    backdrop_path: '/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg',
    genre_ids: [27, 9648, 53],
    id: 1086747,
    original_language: 'en',
    original_title: 'The Watchers',
    overview:
      'Mina, uma artista de 28 anos, que se perde em uma imensa e assustadora floresta natural no oeste da Irlanda. Quando Mina finalmente encontra abrigo, ela acaba presa ao lado de três estranhos que são vigiados e perseguidos por criaturas misteriosas todas as noites.',
    popularity: 43.443,
    poster_path: '/jFpsKOCppRvwP0Igwp0F0Xu1RBJ.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Os Observadores',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/bgPkOllkc6tSLPTGSySm9hetMFs.jpg',
    genre_ids: [18, 80],
    id: 1097175,
    original_language: 'pt',
    original_title: 'Grande Sertão',
    overview:
      'A luta entre policiais e bandidos assumiu ares de uma guerra de verdade: a comunidade é cercada por um enorme muro, helicópteros rondam os céus, batalhões desfilam pelas ruas, os bandidos possuem um verdadeiro exército de guerreiros. Tudo isso se passa na gigantesca periferia urbana chamada de "Grande Sertão". O filme é uma adaptação do clássico literário homônimo de Guimarães Rosa.',
    popularity: 3.617,
    poster_path: '/eG2mub8IdF6JdxuW95FTav7eNTs.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Grande Sertão',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/q8IEFmEGGSGmAWfwRs23XDwdFN4.jpg',
    genre_ids: [878, 28, 12],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'Quando o mundo entra em colapso, a jovem Furiosa é sequestrada do Green Place das Muitas Mães e cai nas mãos da horda de motoqueiros liderada pelo Senhor da Guerra Dementus. Vagando pelo deserto condenado, eles encontram a Cidadela controlada por Immortan Joe. Enquanto os dois tiranos lutam por poder e controle, Furiosa terá que sobreviver a muitos desafios para encontrar e trilhar o caminho de volta para casa.',
    popularity: 434.408,
    poster_path: '/afy34b5II1NgA6paGgHnf4y86w1.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Furiosa: Uma Saga Mad Max',
    video: false,
    vote_average: 8.2,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
    genre_ids: [28, 53],
    id: 560016,
    original_language: 'en',
    original_title: 'Monkey Man',
    overview:
      'Kid é um jovem que ganha a vida em um clube de luta clandestino, onde, usando uma máscara de gorila, é brutalmente espancado todas as noites por lutadores mais populares. Após anos de raiva contida e uma vida muito dura, Kid encontra uma maneira de se infiltrar na elite da cidade. À medida que seu trauma de infância ressurge, ele não mede esforços para acertar as contas com os homens da alta sociedade que tiraram o pouco que ele tinha.',
    popularity: 224.9,
    poster_path: '/ziXIsqVTBrKajZpVEGKiSvot3gu.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Fúria Primitiva',
    video: false,
    vote_average: 7.2,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/9umudqXenMm3kfX7hCTekIH0XWm.jpg',
    genre_ids: [10749, 35, 18],
    id: 891933,
    original_language: 'en',
    original_title: 'Sometimes I Think About Dying',
    overview:
      'Fran gosta de pensar em morrer. Quando ela faz rir um cara no escritório, ele quer mais - um encontro no cinema, uma fatia de torta, uma conversa. Mas se namorar com ele significa aprender a viver, ela tem certeza de que não pode fazer isso.',
    popularity: 18.61,
    poster_path: '/vpcjCTzVoxoxIBmBGpjGrWL4JIV.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Sometimes I Think About Dying',
    video: false,
    vote_average: 6.1,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/PMu7kiBY9OcdXlebOvtYS7E0m9.jpg',
    genre_ids: [35, 10749],
    id: 1184420,
    original_language: 'pt',
    original_title: 'Morando com o Crush',
    overview:
      'Luana e Hugo são colegas de escola e apaixonados um pelo outro. Mas quando a mãe de Hugo e o pai de Luana decidem namorar e mudar de cidade com todos, a situação complica para os pretendentes.',
    popularity: 7.899,
    poster_path: '/eZA7H3FN20qX5ppoCsdUsMSvYk4.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Morando com o Crush',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/4Q3Y3Q1jKMxGrskORNnZlwOTajG.jpg',
    genre_ids: [18],
    id: 1008795,
    original_language: 'pt',
    original_title: 'A Festa de Léo',
    overview:
      'A história retrata a realidade de uma família da favela do Vidigal e se passa nos dias que antecedem a festa de 12 anos de Léo, filho da batalhadora Rita. Ela não mede esforços para fazer uma grande comemoração para o menino, mas, no dia do evento, descobre que o marido, Dudu, envolvido com drogas, roubou todo o dinheiro destinado à festa.  A partir daí, a protagonista vai precisar superar vários obstáculos para resolver o problema e, para isso, terá que contar com a compreensão do garoto e com uma grande rede de apoio dos amigos.',
    popularity: 7.581,
    poster_path: '/M9mKw9YVssnrf04tOj67UPDYBQ.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - A Festa de Léo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: 'en',
    original_title: 'Immaculate',
    overview:
      'Cecilia, uma jovem religiosa, se torna freira em um convento isolado na região rural italiana. Após uma gravidez misteriosa, Cecilia é atormentada por forças perversas, enquanto confronta segredos sombrios e horrores do convento.',
    popularity: 596.447,
    poster_path: '/tsV19P8J4NMP54cC8QCg1IkLLks.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Imaculada',
    video: false,
    vote_average: 6.188,
    vote_count: 463,
  },
  {
    adult: false,
    backdrop_path: '/6LksoR7reQ45gQRik0zhrHmcpZw.jpg',
    genre_ids: [27, 53],
    id: 1010600,
    original_language: 'en',
    original_title: 'The Strangers: Chapter 1',
    overview:
      'Uma jovem viaja para o campo com seu namorado para começar uma nova vida. Quando seu carro quebra, o casal é forçado a passar a noite em uma isolada casa Airbnb, onde a dupla é aterrorizada até o amanhecer por três estranhos mascarados.',
    popularity: 124.438,
    poster_path: '/kiFxBuX0yQTw042MeqCuTZypfYD.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Os Estranhos: Capítulo 1',
    video: false,
    vote_average: 4.65,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: '/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg',
    genre_ids: [16, 18],
    id: 1012201,
    original_language: 'ja',
    original_title: '劇場版ハイキュー!! ゴミ捨て場の決戦',
    overview:
      'Shoyo Hinata se junta ao clube de vôlei do Karasuno High para ser como seu ídolo, um ex-jogador do Karasuno conhecido como o “Pequeno Gigante”. Mas Hinata logo descobre que deve se juntar a seu inimigo do ensino médio, Tobio Kageyama. Seus estilos conflitantes se transformam em uma arma surpreendente, mas será que eles conseguirão derrotar seu rival Nekoma High na tão aguardada “Dumpster Battle”, o tão aguardado confronto final entre duas equipes adversárias?',
    popularity: 87.883,
    poster_path: '/8iPstBjKGHEQcart2JaeJoD64Ht.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - HAIKYU!! A Batalha do Lixo',
    video: false,
    vote_average: 8.7,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/rBo0yYQTruIYEuXdyCAyVVlNb2H.jpg',
    genre_ids: [18],
    id: 974036,
    original_language: 'en',
    original_title: 'Ordinary Angels',
    overview:
      'Inspirado na incrível história real de uma cabeleireira de Louisville, Kentucky, que sozinha, reuniu  uma comunidade inteira para ajudar um pai viúvo a salvar a vida de sua filha de 5 anos gravemente doente, após sua cidade ter sido atingida por uma grande nevasca causada pela onda de frio norte-americana de 1994.',
    popularity: 87.435,
    poster_path: '/7pe1dn5RPxpkEOfOZtXRZAehxv3.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Anjos na Terra',
    video: false,
    vote_average: 7.91,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: '/eDJgcItr9MQm72KjSJkq7rX9SIW.jpg',
    genre_ids: [35, 10402, 10749],
    id: 782718,
    original_language: 'pt',
    original_title: 'Meu Sangue Ferve por Você',
    overview:
      'Em 1979, Magal, um dos artistas mais populares e celebrados do país, segue a rotina de ensaios e compromissos em Salvador. Durante um programa de TV, conhece a deslumbrante Magali e é acometido por uma paixão inédita e avassaladora. Para conquistá-la, precisará vencer a resistência de Jean Pierre, seu empresário passional, além da desconfiança da família, dos amigos e da própria amada.',
    popularity: 3.212,
    poster_path: '/7PrQWs7z5ASojTQRWOilIzm1smr.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Meu Sangue Ferve por Você',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/vvf5frN4sBN2JzBzNedNdbCwLOu.jpg',
    genre_ids: [16, 18, 14],
    id: 1013578,
    original_language: 'pt',
    original_title: 'Dia Zero',
    overview:
      'Durante um dia chuvoso, um homem, que vive na região central de uma cidade grande, tem um dia complicado, além de se ver cada vez mais distante da realidade.',
    popularity: 1.787,
    poster_path: '/9l1RIZZHfvruMA5SqAWAAyAuXny.jpg',
    release_date: '2024-06-01',
    title: 'MOCK PAGE 1 BREVE - Dia Zero',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/JtN7Q03S3oq7A4KZ7Z3I7m3osP.jpg',
    genre_ids: [28, 53, 80],
    id: 573435,
    original_language: 'en',
    original_title: 'Bad Boys: Ride or Die',
    overview:
      'Os Bad Boys preferidos do mundo todo estão de volta com a mistura icônica de ação eletrizante e comédia escrachada, mas, dessa vez, com uma virada: os melhores de Miami são agora os mais procurados.',
    popularity: 114.211,
    poster_path: '/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Bad Boys: Até o Fim',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/z8tvRmo7LvV8P5T9R2GhtUc4MVL.jpg',
    genre_ids: [35],
    id: 1172335,
    original_language: 'pt',
    original_title: 'Mallandro: O Errado que Deu Certo',
    overview:
      'Mallandro perde uma competição de reality show. Incapaz de se deixar abater, Mallandro tenta conseguir novos trabalhos, sempre recorrendo aos seus bordões inimitáveis: rá!,iéié e glu-glu.',
    popularity: 4.433,
    poster_path: '/tIBSze3aeYf2c7l5sca6E3H1hUW.jpg',
    release_date: '2024-06-06',
    title: 'MOCK PAGE 1 BREVE - Mallandro: O Errado que Deu Certo',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
]

const MOCK_REMOVE_VIDEOS_ARE_NOT_YOUTUBE_FORMATTED = [
  {
    iso_639_1: 'pt',
    iso_3166_1: 'BR',
    name: 'Teaser Oficial Legendado',
    key: 'HaHUDCFTM8A',
    site: 'YouTube',
    size: 1080,
    type: 'Trailer',
    official: true,
    published_at: '2023-11-02T18:24:33.000Z',
    id: '6543ee907719d700adc5024d',
  },
  {
    iso_639_1: 'pt',
    iso_3166_1: 'BR',
    name: 'Teaser Oficial Dublado',
    key: 'k2A0A1gehLg',
    site: 'YouTube',
    size: 1080,
    type: 'Trailer',
    official: true,
    published_at: '2023-11-02T18:23:45.000Z',
    id: '6543ee809d6e330100f5d750',
  },
]

const MOCK_MOVIE_WITHOUT_INFOS_FORMATTED = [
  {
    adult: false,
    backdrop_path: '/q8IEFmEGGSGmAWfwRs23XDwdFN4.jpg',
    genre_ids: [878, 28, 12],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'Quando o mundo entra em colapso, a jovem Furiosa é sequestrada do Green Place das Muitas Mães e cai nas mãos da horda de motoqueiros liderada pelo Senhor da Guerra Dementus. Vagando pelo deserto condenado, eles encontram a Cidadela controlada por Immortan Joe. Enquanto os dois tiranos lutam por poder e controle, Furiosa terá que sobreviver a muitos desafios para encontrar e trilhar o caminho de volta para casa.',
    popularity: 434.408,
    poster_path: '/afy34b5II1NgA6paGgHnf4y86w1.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Furiosa: Uma Saga Mad Max',
    video: false,
    vote_average: 8.2,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
    genre_ids: [28, 53],
    id: 560016,
    original_language: 'en',
    original_title: 'Monkey Man',
    overview:
      'Kid é um jovem que ganha a vida em um clube de luta clandestino, onde, usando uma máscara de gorila, é brutalmente espancado todas as noites por lutadores mais populares. Após anos de raiva contida e uma vida muito dura, Kid encontra uma maneira de se infiltrar na elite da cidade. À medida que seu trauma de infância ressurge, ele não mede esforços para acertar as contas com os homens da alta sociedade que tiraram o pouco que ele tinha.',
    popularity: 224.9,
    poster_path: '/ziXIsqVTBrKajZpVEGKiSvot3gu.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Fúria Primitiva',
    video: false,
    vote_average: 7.2,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/9umudqXenMm3kfX7hCTekIH0XWm.jpg',
    genre_ids: [10749, 35, 18],
    id: 891933,
    original_language: 'en',
    original_title: 'Sometimes I Think About Dying',
    overview:
      'Fran gosta de pensar em morrer. Quando ela faz rir um cara no escritório, ele quer mais - um encontro no cinema, uma fatia de torta, uma conversa. Mas se namorar com ele significa aprender a viver, ela tem certeza de que não pode fazer isso.',
    popularity: 18.61,
    poster_path: '/vpcjCTzVoxoxIBmBGpjGrWL4JIV.jpg',
    release_date: '2024-05-23',
    title: 'MOCK PAGE 1 BREVE - Sometimes I Think About Dying',
    video: false,
    vote_average: 6.1,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: 'en',
    original_title: 'Immaculate',
    overview:
      'Cecilia, uma jovem religiosa, se torna freira em um convento isolado na região rural italiana. Após uma gravidez misteriosa, Cecilia é atormentada por forças perversas, enquanto confronta segredos sombrios e horrores do convento.',
    popularity: 596.447,
    poster_path: '/tsV19P8J4NMP54cC8QCg1IkLLks.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Imaculada',
    video: false,
    vote_average: 6.188,
    vote_count: 463,
  },
  {
    adult: false,
    backdrop_path: '/6LksoR7reQ45gQRik0zhrHmcpZw.jpg',
    genre_ids: [27, 53],
    id: 1010600,
    original_language: 'en',
    original_title: 'The Strangers: Chapter 1',
    overview:
      'Uma jovem viaja para o campo com seu namorado para começar uma nova vida. Quando seu carro quebra, o casal é forçado a passar a noite em uma isolada casa Airbnb, onde a dupla é aterrorizada até o amanhecer por três estranhos mascarados.',
    popularity: 124.438,
    poster_path: '/kiFxBuX0yQTw042MeqCuTZypfYD.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Os Estranhos: Capítulo 1',
    video: false,
    vote_average: 4.65,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: '/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg',
    genre_ids: [16, 18],
    id: 1012201,
    original_language: 'ja',
    original_title: '劇場版ハイキュー!! ゴミ捨て場の決戦',
    overview:
      'Shoyo Hinata se junta ao clube de vôlei do Karasuno High para ser como seu ídolo, um ex-jogador do Karasuno conhecido como o “Pequeno Gigante”. Mas Hinata logo descobre que deve se juntar a seu inimigo do ensino médio, Tobio Kageyama. Seus estilos conflitantes se transformam em uma arma surpreendente, mas será que eles conseguirão derrotar seu rival Nekoma High na tão aguardada “Dumpster Battle”, o tão aguardado confronto final entre duas equipes adversárias?',
    popularity: 87.883,
    poster_path: '/8iPstBjKGHEQcart2JaeJoD64Ht.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - HAIKYU!! A Batalha do Lixo',
    video: false,
    vote_average: 8.7,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/rBo0yYQTruIYEuXdyCAyVVlNb2H.jpg',
    genre_ids: [18],
    id: 974036,
    original_language: 'en',
    original_title: 'Ordinary Angels',
    overview:
      'Inspirado na incrível história real de uma cabeleireira de Louisville, Kentucky, que sozinha, reuniu  uma comunidade inteira para ajudar um pai viúvo a salvar a vida de sua filha de 5 anos gravemente doente, após sua cidade ter sido atingida por uma grande nevasca causada pela onda de frio norte-americana de 1994.',
    popularity: 87.435,
    poster_path: '/7pe1dn5RPxpkEOfOZtXRZAehxv3.jpg',
    release_date: '2024-05-30',
    title: 'MOCK PAGE 1 BREVE - Anjos na Terra',
    video: false,
    vote_average: 7.91,
    vote_count: 89,
  },
]

const MOCK_FILTER_CLASSIFICATIONS_BY_REGION_FORMATTED = [
  {
    country: 'BR',
    certification: '12',
    color: '#ffcc00',
  },
  {
    country: 'US',
    certification: 'PG-13',
    color: '#ff6600',
  },
  {
    country: 'US',
    certification: 'PG-13',
    color: '#ff6600',
  },
  {
    country: 'US',
    certification: 'PG-13',
    color: '#ff6600',
  },
]

const MOCK_FILTER_WATCH_WITH_INFOS_FORMATTED = {
  ads: [
    {
      logo_path: '/9ghgSC0MA082EL6HLCW3GalykFD.jpg',
      provider_id: 2,
      provider_name: 'Apple TV',
      display_priority: 10,
    },
  ],
  buy: [
    {
      logo_path: '/9ghgSC0MA082EL6HLCW3GalykFD.jpg',
      provider_id: 2,
      provider_name: 'Apple TV',
      display_priority: 10,
    },
    {
      logo_path: '/seGSXajazLMCKGB5hnRCidtjay1.jpg',
      provider_id: 10,
      provider_name: 'Amazon Video',
      display_priority: 16,
    },
    {
      logo_path: '/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg',
      provider_id: 3,
      provider_name: 'Google Play Movies',
      display_priority: 17,
    },
    {
      logo_path: '/5vfrJQgNe9UnHVgVNAwZTy0Jo9o.jpg',
      provider_id: 68,
      provider_name: 'Microsoft Store',
      display_priority: 18,
    },
  ],
  flatrate: [
    {
      logo_path: '/fksCUZ9QDWZMUwL2LgMtLckROUN.jpg',
      provider_id: 1899,
      provider_name: 'Max',
      display_priority: 8,
    },
    {
      logo_path: '/xzN54gRvHqG9CkJPYPeS6DmJokS.jpg',
      provider_id: 484,
      provider_name: 'NOW',
      display_priority: 28,
    },
  ],
  rent: [
    {
      logo_path: '/9ghgSC0MA082EL6HLCW3GalykFD.jpg',
      provider_id: 2,
      provider_name: 'Apple TV',
      display_priority: 10,
    },
    {
      logo_path: '/seGSXajazLMCKGB5hnRCidtjay1.jpg',
      provider_id: 10,
      provider_name: 'Amazon Video',
      display_priority: 16,
    },
    {
      logo_path: '/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg',
      provider_id: 3,
      provider_name: 'Google Play Movies',
      display_priority: 17,
    },
    {
      logo_path: '/5vfrJQgNe9UnHVgVNAwZTy0Jo9o.jpg',
      provider_id: 68,
      provider_name: 'Microsoft Store',
      display_priority: 18,
    },
  ],
}

describe('movies', () => {
  it('sortByReleaseDateAsc', () => {
    const mock = [...MOCK_GET_UPCOMING_PAGE_1.results]
    const SUT = sortByReleaseDateAsc(mock)
    const expected = MOCK_SORT_BY_RELEASE_DATE_ASC_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('sortByReleaseDateDesc', () => {
    const mock = [...MOCK_GET_UPCOMING_PAGE_1.results]
    const SUT = sortByReleaseDateDesc(mock)
    const expected = MOCK_SORT_BY_RELEASE_DATE_DESC_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('removeMovieWithoutThumbnail', () => {
    const mock = [...MOCK_GET_UPCOMING_PAGE_1.results]
    const SUT = removeMovieWithoutThumbnail(mock)
    const expected = MOCK_REMOVE_MOVIE_WITHOUT_THUMBNAIL_FORMATTED
    expect(SUT).toStrictEqual(expected)

    expected.forEach((movie) => {
      expect(movie.backdrop_path).toBeTypeOf('string')
      expect(movie.poster_path).toBeTypeOf('string')
    })
  })

  it('removeVideosAreNotYouTube', () => {
    const mock = [...MOCK_GET_VIDEOS.results]
    const SUT = removeVideosAreNotYouTube(mock)
    const expected = MOCK_REMOVE_VIDEOS_ARE_NOT_YOUTUBE_FORMATTED
    expect(SUT).toStrictEqual(expected)

    expected.forEach((video) => {
      expect(video.site).toStrictEqual('YouTube')
      expect(video.key).toBeTypeOf('string')
      expect(video.official).toBe(true)
    })
  })

  it('removeMovieWithoutInfos', () => {
    const mock = [...MOCK_GET_UPCOMING_PAGE_1.results]
    const SUT = removeMovieWithoutInfos(mock)
    const expected = MOCK_MOVIE_WITHOUT_INFOS_FORMATTED
    expect(SUT).toStrictEqual(expected)

    expected.forEach((movie) => {
      expect(movie.backdrop_path).toBeTypeOf('string')
      expect(movie.poster_path).toBeTypeOf('string')
      expect(movie.id).toBeTypeOf('number')
      expect(movie.title).toBeTypeOf('string')
      expect(movie.overview).toBeTypeOf('string')
      expect(movie.vote_average).toBeTypeOf('number')
    })
  })

  it('filterClassificationsByRegion', () => {
    const mock = [...MOCK_GET_CLASSIFICATIONS.results]
    const SUT = filterClassificationsByRegion(mock)
    const expected = MOCK_FILTER_CLASSIFICATIONS_BY_REGION_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })

  it('filterWatchWithInfos', () => {
    const mock = MOCK_GET_WATCH.results.BR
    const SUT = filterWatchWithInfos(mock)
    const expected = MOCK_FILTER_WATCH_WITH_INFOS_FORMATTED
    expect(SUT).toStrictEqual(expected)
  })
})
